"""Task 290 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('notbg', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('tcoef', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQAC8')),
        tensor('W', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAA8')),
        tensor('z', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPA==')),
        tensor('c3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQg==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'notbg'], ['cnb32'], equation='bchw,c->bc'),
        helper.make_node('Cast', ['cnb32'], ['cnb'], to=10),
        helper.make_node('ReduceSum', ['cnb'], ['total'], axes=[1], keepdims=1),
        helper.make_node('Sqrt', ['total'], ['N']),
        helper.make_node('Shrink', ['cnb'], ['d'], bias=5.0, lambd=0.0),
        helper.make_node('Sub', ['N', 'c3'], ['a']),
        helper.make_node('Sub', ['a', 'one'], ['b']),
        helper.make_node('Sub', ['b', 'one'], ['c']),
        helper.make_node('Sub', ['c', 'one'], ['e']),
        helper.make_node('Mul', ['a', 'b'], ['ab']),
        helper.make_node('Mul', ['ab', 'c'], ['abc']),
        helper.make_node('Mul', ['c', 'e'], ['ce']),
        helper.make_node('Concat', ['z', 'ce', 'a', 'abc', 'z', 'z'], ['cen'], axis=2),
        helper.make_node('Concat', ['one', 'one', 'one', 'a', 'ab', 'abc'], ['sq'], axis=2),
        helper.make_node('Concat', ['cen', 'sq'], ['r6'], axis=1),
        helper.make_node('Conv', ['r6', 'W'], ['r30'], group=2, kernel_shape=[1], pads=[0, 24]),
        helper.make_node('Einsum', ['d', 'tcoef', 'r30', 'r30'], ['output'], equation='bk,t,bti,btj->bkij'),
    ]
    value_infos = [
    ]
    return model('task290_live_exact', nodes, inits, output_dtype=10, opset=12, value_infos=value_infos)
