"""Task 202 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('cnt', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('val', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('bg', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'cnt'], ['rcnt'], equation='bchw,kc->hk'),
        helper.make_node('Einsum', ['input', 'val'], ['rsum'], equation='bchw,kc->hk'),
        helper.make_node('Einsum', ['input', 'cnt'], ['ccnt'], equation='bchw,kc->kw'),
        helper.make_node('Einsum', ['input', 'val'], ['csum'], equation='bchw,kc->kw'),
        helper.make_node('Einsum', ['input', 'input', 'val', 'val', 'cnt'], ['ia'], equation='bchw,bdhx,ac,fc,ed->'),
        helper.make_node('Einsum', ['rsum', 'rsum'], ['ib'], equation='hi,hi->'),
        helper.make_node('Equal', ['ia', 'ib'], ['gate']),
        helper.make_node('Cast', ['rcnt'], ['rcnt16'], to=10),
        helper.make_node('Cast', ['rsum'], ['rsum16'], to=10),
        helper.make_node('Cast', ['ccnt'], ['ccnt16'], to=10),
        helper.make_node('Cast', ['csum'], ['csum16'], to=10),
        helper.make_node('Div', ['rsum16', 'rcnt16'], ['rcolor']),
        helper.make_node('Div', ['csum16', 'ccnt16'], ['ccolor']),
        helper.make_node('ReduceMax', ['rsum16'], ['rmax'], axes=[0], keepdims=1),
        helper.make_node('ReduceMax', ['csum16'], ['cmax'], axes=[1], keepdims=1),
        helper.make_node('Sub', ['rmax', 'rsum16'], ['rdef']),
        helper.make_node('Sub', ['cmax', 'csum16'], ['cdef']),
        helper.make_node('Where', ['gate', 'rcolor', 'rdef'], ['A']),
        helper.make_node('Where', ['gate', 'cdef', 'ccolor'], ['B']),
        helper.make_node('Equal', ['A', 'B'], ['selected']),
        helper.make_node('Where', ['selected', 'bg', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task202_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
