"""Task 236 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('w_pair', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAyLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAvwAAAAAAAADDAAD+QgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('w_route', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAD/AAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ConvTranspose', ['input', 'w_pair'], ['parity_code_f32'], dilations=[5, 1], pads=[5, 0, 26, 26], strides=[1, 1]),
        helper.make_node('Cast', ['parity_code_f32'], ['parity_code_i8'], to=3),
        helper.make_node('Shrink', ['parity_code_i8'], ['signed_parity_i8'], bias=127.0, lambd=0.0),
        helper.make_node('ConvInteger', ['signed_parity_i8', 'w_route'], ['output'], pads=[0, 0, 26, 26], strides=[1, 1]),
    ]
    value_infos = [
    ]
    return model('task236_live_exact', nodes, inits, output_dtype=6, opset=13, value_infos=value_infos)
