"""Task 223 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('rois', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDUpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAACamTlAmpk5QA==')),
    ]
    nodes = [
        helper.make_node('MaxRoiPool', ['input', 'rois'], ['output'], pooled_shape=[30, 30], spatial_scale=3.0),
    ]
    value_infos = [
    ]
    return model('task223_live_exact', nodes, inits, output_dtype=1, opset=11, value_infos=value_infos)
