"""Task 197 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sentinel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoASQ==')),
        tensor('fill', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAKAAAACgAAAA==')),
        tensor('channels_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('col_idx_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input'], ['g1_sliced'], ends=[1, 10, 2, 10], starts=[0, 0, 1, 0]),
        helper.make_node('ArgMax', ['g1_sliced'], ['g1_am'], axis=1, keepdims=0),
        helper.make_node('Cast', ['g1_am'], ['g1_ref'], to=6),
        helper.make_node('Squeeze', ['g1_ref'], ['g1_ref_i'], axes=[0, 1]),
        helper.make_node('Unsqueeze', ['g1_ref_i'], ['g1_ref_u'], axes=[0]),
        helper.make_node('Equal', ['g1_ref_u', 'channels_u'], ['eq_mat']),
        helper.make_node('Where', ['eq_mat', 'col_idx_u', 'sentinel'], ['masked']),
        helper.make_node('ReduceMin', ['masked'], ['first_occ_f16'], axes=[1], keepdims=0),
        helper.make_node('Gather', ['first_occ_f16', 'g1_ref_i'], ['first_occ'], axis=0),
        helper.make_node('Cast', ['first_occ'], ['indices_10'], to=6),
        helper.make_node('Concat', ['indices_10', 'fill'], ['indices'], axis=0),
        helper.make_node('Gather', ['input', 'indices'], ['output'], axis=3),
    ]
    value_infos = [
    ]
    return model('task197_live_exact', nodes, inits, output_dtype=1, opset=9, value_infos=value_infos)
