"""Task 058 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('T', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo0mJBAKJmWQJM4pcDa1Tm/hT0FwCJEW0CeWN5AnHq4P/LhoD9B/LVAOQSlwCa4CMBmTeK/mSq0QAE+yEA/CRk/SlHuv1qt0kDF6YjA5RghwO4CKsDwv6dAC1JnQIK22b/5oS3AAHYJQR6YNMA1LIm/1utvwH5p5UDooFRAGXKXwKEzuMCWFeFAXZsdwKfrHr+Troe/+H27QE3kH0ARapPA9H9zwMZ7mkATcby/ijjLP4reOL8QeSxARc2xP0wIksDboEzAzfRIQJeYp7/5RSVAWuDZPmo/vj/Eeqk/yuCLwFR8VcDl2cs/LCS7vw8HNUCS28+9R1O2PbWeRj/pGHjARDkIwNQHlT/SkaC/GZhKQKfbXz+V90W+jkSCP52jfMCSxdu/+udaP3mktr9Y14JAlyJQP4UFIz4Xj7e/ORrOv8yiSD6PTok+EoYxvq/lNz6ejKI9JcpuvlkcpDsrHle9XXugPiLmkz2zGoQ9yZU3PayEkz1j18q9GOSEvptdLb5FIUO+hDONvHQqJLsIuVQ+VcvmvT/cQ7ugnnY9k8QfPvXhrT4z/3w+DqhOPpbEk75A+EI+HVu2PsmHbr1M9yw+0QSqPTnKVLyRGQu+G4BgvrWiI75vl/e9MBuWPhJRdT0=')),
        tensor('A', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArVIPI/NUa9wIB9g0ANA5S/SSUJQAXQl8A0cZxAky00wK34f0ANFqvAJpTQQD9xt0B/S5/AvvKswBWWTkDL8h9ArhlOwAXDj8BbJ4ZAS0krQBkvXcCTV6fApMnEQCXrKEBXjQrAnwf9wNQp1kAyecU/KX9nvyJb3cDE+atAlEQFPg==')),
        tensor('Core', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDQsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIB2A/gkTyvfPNOkAJbYa/GIWxv06/SkDV4c/AevuWQM2gHUBs0QXBHiCIv/hMKEA/pQHAS7kVQESI8z+NnhHALrgmQFYBkcDhG5W/VPyrvytZnMCOJSC/T6bFP6Re00DMGk6/0pWfQPql/D7Pghy+2zsMwNaksUBVQmG+eRttwA==')),
        tensor('chan', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('sixteen', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoQ')),
    ]
    nodes = [
        helper.make_node('ReduceL2', ['input'], ['n'], keepdims=0),
        helper.make_node('Cast', ['n'], ['n_u8'], to=2),
        helper.make_node('Mod', ['n_u8', 'sixteen'], ['idx_u8']),
        helper.make_node('Cast', ['idx_u8'], ['idx'], to=6),
        helper.make_node('Gather', ['A', 'idx'], ['a2'], axis=0),
        helper.make_node('Einsum', ['input', 'a2', 'chan', 'Core', 'T', 'T'], ['output'], equation='achw,p,k,prs,hr,ws->akhw'),
    ]
    value_infos = [
    ]
    return model('task058_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
