"""Task 359 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axW', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('axH', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('one8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('fifty8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoy')),
        tensor('chidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input', 'axW'], ['rc'], keepdims=1),
        helper.make_node('ReduceSum', ['input', 'axH'], ['cc'], keepdims=1),
        helper.make_node('ArgMax', ['rc'], ['rlab64'], axis=1, keepdims=1),
        helper.make_node('ArgMax', ['cc'], ['clab64'], axis=1, keepdims=1),
        helper.make_node('Cast', ['rlab64'], ['rlab'], to=3),
        helper.make_node('Cast', ['clab64'], ['clab'], to=3),
        helper.make_node('ReduceMax', ['rc'], ['rmaxc'], axes=[1], keepdims=1),
        helper.make_node('ReduceMax', ['cc'], ['cmaxc'], axes=[1], keepdims=1),
        helper.make_node('ReduceSum', ['rmaxc'], ['rmatch'], keepdims=0),
        helper.make_node('ReduceSum', ['cmaxc'], ['cmatch'], keepdims=0),
        helper.make_node('Greater', ['cmatch', 'rmatch'], ['col_wins']),
        helper.make_node('Not', ['col_wins'], ['row_wins']),
        helper.make_node('Cast', ['row_wins'], ['c'], to=3),
        helper.make_node('Sub', ['one8', 'c'], ['nc']),
        helper.make_node('Mul', ['rlab', 'c'], ['rterm']),
        helper.make_node('Mul', ['clab', 'nc'], ['cterm']),
        helper.make_node('Greater', ['rmaxc', 'zero_f'], ['rnon']),
        helper.make_node('Greater', ['cmaxc', 'zero_f'], ['cnon']),
        helper.make_node('Cast', ['rnon'], ['rnon8'], to=3),
        helper.make_node('Cast', ['cnon'], ['cnon8'], to=3),
        helper.make_node('Add', ['rterm', 'fifty8'], ['rA0']),
        helper.make_node('Mul', ['rA0', 'rnon8'], ['rA1']),
        helper.make_node('Sub', ['rA1', 'fifty8'], ['rA']),
        helper.make_node('Add', ['cterm', 'fifty8'], ['cB0']),
        helper.make_node('Mul', ['cB0', 'cnon8'], ['cB1']),
        helper.make_node('Sub', ['cB1', 'fifty8'], ['cB']),
        helper.make_node('Sub', ['chidx', 'cB'], ['D']),
        helper.make_node('Equal', ['rA', 'D'], ['output']),
    ]
    value_infos = [
    ]
    return model('task359_live_exact', nodes, inits, output_dtype=9, opset=17, value_infos=value_infos)
