"""Task 226 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('row_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAABAAAAAAAAAA==')),
        tensor('col_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAAAQAAAAAAAAAKAAAAAAAAAA==')),
        tensor('pads_6_to_10_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_starts', 'row_ends'], ['row_sep_f']),
        helper.make_node('Slice', ['input', 'slice_starts', 'col_ends'], ['col_sep_f']),
        helper.make_node('Cast', ['row_sep_f'], ['row_sep'], to=2),
        helper.make_node('Cast', ['col_sep_f'], ['col_sep'], to=2),
        helper.make_node('Sub', ['one', 'row_sep'], ['row_non']),
        helper.make_node('Sub', ['one', 'col_sep'], ['col_non']),
        helper.make_node('Split', ['row_non'], ['r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9'], axis=2),
        helper.make_node('Split', ['col_non'], ['c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9'], axis=3),
        helper.make_node('Sub', ['r0', 'r0'], ['z']),
        helper.make_node('Mul', ['r1', 'r2'], ['r12']),
        helper.make_node('Mul', ['r3', 'r4'], ['r34']),
        helper.make_node('Mul', ['r5', 'r6'], ['r56']),
        helper.make_node('Mul', ['r7', 'r8'], ['r78']),
        helper.make_node('Mul', ['c1', 'c2'], ['c12']),
        helper.make_node('Mul', ['c12', 'c3'], ['c123']),
        helper.make_node('Mul', ['c3', 'c4'], ['c34']),
        helper.make_node('Mul', ['c2', 'c34'], ['c234']),
        helper.make_node('Mul', ['c5', 'c6'], ['c56']),
        helper.make_node('Mul', ['c56', 'c7'], ['c567']),
        helper.make_node('Mul', ['c7', 'c8'], ['c78']),
        helper.make_node('Mul', ['c6', 'c78'], ['c678']),
        helper.make_node('Concat', ['r0', 'r1', 'r12', 'z', 'z', 'z', 'z', 'z', 'z', 'z'], ['row_first'], axis=2),
        helper.make_node('Concat', ['z', 'z', 'z', 'r34', 'r4', 'r5', 'r56', 'z', 'z', 'z'], ['row_mid'], axis=2),
        helper.make_node('Concat', ['z', 'z', 'z', 'z', 'z', 'z', 'z', 'r78', 'r8', 'r9'], ['row_last'], axis=2),
        helper.make_node('Concat', ['c0', 'c1', 'c12', 'c123', 'z', 'z', 'z', 'z', 'z', 'z'], ['col_first'], axis=3),
        helper.make_node('Concat', ['z', 'z', 'c234', 'c34', 'c4', 'c5', 'c56', 'c567', 'z', 'z'], ['col_mid'], axis=3),
        helper.make_node('Concat', ['z', 'z', 'z', 'z', 'z', 'z', 'c678', 'c78', 'c8', 'c9'], ['col_last'], axis=3),
        helper.make_node('Max', ['row_sep', 'col_sep'], ['ch5']),
        helper.make_node('Mul', ['row_first', 'col_first'], ['ch1']),
        helper.make_node('Mul', ['row_mid', 'col_mid'], ['ch2']),
        helper.make_node('Mul', ['row_last', 'col_last'], ['ch3']),
        helper.make_node('Max', ['ch1', 'ch2', 'ch3', 'ch5'], ['union']),
        helper.make_node('Sub', ['one', 'union'], ['ch0']),
        helper.make_node('Sub', ['ch1', 'ch1'], ['ch4']),
        helper.make_node('Concat', ['ch0', 'ch1', 'ch2', 'ch3', 'ch4', 'ch5'], ['out6'], axis=1),
        helper.make_node('Pad', ['out6', 'pads_6_to_10_30'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task226_live_exact', nodes, inits, output_dtype=2, opset=14, value_infos=value_infos)
