"""Task 215 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('idx3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAADAAAABAAAAAUAAAA=')),
        tensor('idx4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAAGAAAABAAAAAUAAAA=')),
        tensor('rownum', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0AAAA=')),
        tensor('c29', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAodAAAA')),
        tensor('sumax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('bs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAMAAAAAAAAA')),
        tensor('be', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAQAAAAAAAAA')),
        tensor('bax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['totf'], keepdims=0),
        helper.make_node('ReduceMax', ['input'], ['hrow'], axes=[1, 3], keepdims=0),
        helper.make_node('ReduceSum', ['hrow', 'sumax'], ['Hf'], keepdims=0),
        helper.make_node('Cast', ['Hf'], ['Hi'], to=6),
        helper.make_node('Div', ['totf', 'Hf'], ['Wf']),
        helper.make_node('Slice', ['input', 'bs', 'be', 'bax'], ['ch0r3']),
        helper.make_node('ReduceSum', ['ch0r3'], ['bgcf'], keepdims=0),
        helper.make_node('Less', ['bgcf', 'Wf'], ['is3r']),
        helper.make_node('Where', ['is3r', 'idx3', 'idx4'], ['idxt']),
        helper.make_node('Less', ['rownum', 'Hi'], ['rmask']),
        helper.make_node('Where', ['rmask', 'idxt', 'c29'], ['idxf']),
        helper.make_node('Gather', ['input', 'idxf'], ['output'], axis=2),
    ]
    value_infos = [
    ]
    return model('task215_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
