"""Task 168 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ch0_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('ch0_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAACQAAAAAAAAAJAAAAAAAAAA==')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('scale_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('detector_w_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('nonblack_channels', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('ray_w_diag', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAB')),
        tensor('ray_w_anti', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAA')),
        tensor('detector_w0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB////')),
        tensor('detector_w1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/Af//')),
        tensor('detector_w2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr//wH/')),
        tensor('detector_w3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr///8B')),
        tensor('pad18_pads_14_13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('pad18_axes_14_14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'ch0_starts', 'ch0_ends'], ['ch0_8']),
        helper.make_node('Cast', ['ch0_8'], ['black_u8'], to=2),
        helper.make_node('ReduceMax', ['input', 'pad18_axes_14_14'], ['color_presence'], keepdims=1),
        helper.make_node('Mul', ['color_presence', 'nonblack_channels'], ['color_onehot_f']),
        helper.make_node('QLinearConv', ['black_u8', 'scale_f', 'zero_u8', 'detector_w0', 'scale_f', 'detector_w_zero', 'scale_f', 'zero_u8'], ['seed0'], kernel_shape=[2, 2]),
        helper.make_node('QLinearConv', ['seed0', 'scale_f', 'zero_u8', 'ray_w_diag', 'scale_f', 'zero_u8', 'scale_f', 'zero_u8'], ['ray0'], kernel_shape=[7, 7], pads=[0, 0, 9, 9]),
        helper.make_node('QLinearConv', ['black_u8', 'scale_f', 'zero_u8', 'detector_w1', 'scale_f', 'detector_w_zero', 'scale_f', 'zero_u8'], ['seed1'], kernel_shape=[2, 2]),
        helper.make_node('QLinearConv', ['seed1', 'scale_f', 'zero_u8', 'ray_w_anti', 'scale_f', 'zero_u8', 'scale_f', 'zero_u8'], ['ray1'], kernel_shape=[7, 7], pads=[0, 9, 9, 0]),
        helper.make_node('QLinearConv', ['black_u8', 'scale_f', 'zero_u8', 'detector_w2', 'scale_f', 'detector_w_zero', 'scale_f', 'zero_u8'], ['seed2'], kernel_shape=[2, 2]),
        helper.make_node('QLinearConv', ['seed2', 'scale_f', 'zero_u8', 'ray_w_anti', 'scale_f', 'zero_u8', 'scale_f', 'zero_u8'], ['ray2'], kernel_shape=[7, 7], pads=[9, 0, 0, 9]),
        helper.make_node('QLinearConv', ['black_u8', 'scale_f', 'zero_u8', 'detector_w3', 'scale_f', 'detector_w_zero', 'scale_f', 'zero_u8'], ['seed3'], kernel_shape=[2, 2]),
        helper.make_node('QLinearConv', ['seed3', 'scale_f', 'zero_u8', 'ray_w_diag', 'scale_f', 'zero_u8', 'scale_f', 'zero_u8'], ['ray3'], kernel_shape=[7, 7], pads=[9, 9, 0, 0]),
        helper.make_node('Max', ['ray0', 'ray1', 'ray2', 'ray3'], ['ray_scores']),
        helper.make_node('Cast', ['ray_scores'], ['ray_b10'], to=9),
        helper.make_node('Pad', ['ray_b10', 'pad18_pads_14_13', '', 'pad18_axes_14_14'], ['ray_b30'], mode='constant'),
        helper.make_node('Where', ['ray_b30', 'color_onehot_f', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('ch0_8', 1, [1, 1, 8, 8]),
        helper.make_tensor_value_info('black_u8', 2, [1, 1, 8, 8]),
        helper.make_tensor_value_info('color_presence', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('color_onehot_f', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('seed0', 2, [1, 1, 7, 7]),
        helper.make_tensor_value_info('ray0', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('seed1', 2, [1, 1, 7, 7]),
        helper.make_tensor_value_info('ray1', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('seed2', 2, [1, 1, 7, 7]),
        helper.make_tensor_value_info('ray2', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('seed3', 2, [1, 1, 7, 7]),
        helper.make_tensor_value_info('ray3', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_scores', 2, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_b10', 9, [1, 1, 10, 10]),
        helper.make_tensor_value_info('ray_b30', 9, [1, 1, 30, 30]),
    ]
    return model('task168_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
