"""Task 218 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('channel_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAACAQAAAAAAAAAAAAAAAAAAAoEAAAAAAAAAAAAAAAAAAAMBAAAAAAAAAAAAAAAAAAADgQAAAAAAAAAAAAAAAAAAAAEEAAAAAAAAAAAAAAAAAABBBAAAAAAAAAAAAAAAA')),
        tensor('row_diff_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AAAgwQAAyMIAAHrEAEAcxgBQw8cAJHTJAACAPwAAIEEAAMhCAAB6RABAHEYAUMNHACR0SQ==')),
        tensor('col_diff_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AACAPwAAIMEAACBBAADIwgAAyEIAAHrEAAB6RABAHMYAQBxGAFDDxwBQw0cAJHTJACR0SQ==')),
        tensor('topk_k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('rank_scores', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDcsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoARwBGAEUARABCAEAAPA==')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('palette', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDksIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAk=')),
        tensor('pad_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
        tensor('row_valid_col_18_axes13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('_mf_masked_colors_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'channel_weights'], ['sample_grid'], dilations=[9, 9], strides=[3, 3]),
        helper.make_node('Cast', ['sample_grid'], ['sample_grid_u8'], to=2),
        helper.make_node('Conv', ['sample_grid', 'row_diff_weights'], ['row_diff'], pads=[1, 0, 0, 0]),
        helper.make_node('Conv', ['sample_grid', 'col_diff_weights'], ['col_diff'], pads=[0, 1, 0, 0]),
        helper.make_node('Cast', ['row_diff'], ['row_changed_full'], to=9),
        helper.make_node('Squeeze', ['row_changed_full'], ['row_start']),
        helper.make_node('Where', ['row_start', 'rank_scores', 'zero_f16'], ['row_scores']),
        helper.make_node('TopK', ['row_scores', 'topk_k'], ['row_top_values', 'row_idx'], axis=0, largest=1, sorted=1),
        helper.make_node('Cast', ['row_top_values'], ['row_valid'], to=9),
        helper.make_node('Cast', ['col_diff'], ['col_changed_full'], to=9),
        helper.make_node('Squeeze', ['col_changed_full'], ['col_start']),
        helper.make_node('Where', ['col_start', 'rank_scores', 'zero_f16'], ['col_scores']),
        helper.make_node('TopK', ['col_scores', 'topk_k'], ['col_top_values', 'col_idx'], axis=0, largest=1, sorted=1),
        helper.make_node('Cast', ['col_top_values'], ['col_valid'], to=9),
        helper.make_node('Gather', ['sample_grid_u8', 'row_idx'], ['sample_rows'], axis=2),
        helper.make_node('Gather', ['sample_rows', 'col_idx'], ['sample_colors'], axis=3),
        helper.make_node('Unsqueeze', ['row_valid', 'row_valid_col_18_axes13'], ['row_valid_col']),
        helper.make_node('Where', ['row_valid_col', '_mf_masked_colors_c', 'zero_u8'], ['_mf_masked_colors_w1']),
        helper.make_node('Where', ['col_valid', '_mf_masked_colors_c', 'zero_u8'], ['_mf_masked_colors_w2']),
        helper.make_node('Min', ['sample_colors', '_mf_masked_colors_w1', '_mf_masked_colors_w2'], ['masked_colors']),
        helper.make_node('Equal', ['masked_colors', 'palette'], ['onehot_bool']),
        helper.make_node('Pad', ['onehot_bool', 'pad_pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('sample_grid', 1, [1, 1, 7, 7]),
        helper.make_tensor_value_info('sample_grid_u8', 2, [1, 1, 7, 7]),
        helper.make_tensor_value_info('row_diff', 1, [1, 1, 7, 1]),
        helper.make_tensor_value_info('col_diff', 1, [1, 1, 1, 7]),
        helper.make_tensor_value_info('row_changed_full', 9, [1, 1, 7, 1]),
        helper.make_tensor_value_info('row_start', 9, [7]),
        helper.make_tensor_value_info('row_scores', 10, [7]),
        helper.make_tensor_value_info('row_top_values', 10, [3]),
        helper.make_tensor_value_info('row_idx', 7, [3]),
        helper.make_tensor_value_info('row_valid', 9, [3]),
        helper.make_tensor_value_info('col_changed_full', 9, [1, 1, 1, 7]),
        helper.make_tensor_value_info('col_start', 9, [7]),
        helper.make_tensor_value_info('col_scores', 10, [7]),
        helper.make_tensor_value_info('col_top_values', 10, [3]),
        helper.make_tensor_value_info('col_idx', 7, [3]),
        helper.make_tensor_value_info('col_valid', 9, [3]),
        helper.make_tensor_value_info('sample_rows', 2, [1, 1, 3, 7]),
        helper.make_tensor_value_info('sample_colors', 2, [1, 1, 3, 3]),
        helper.make_tensor_value_info('row_valid_col', 9, [3, 1]),
        helper.make_tensor_value_info('_mf_masked_colors_w1', 2, [3, 1]),
        helper.make_tensor_value_info('_mf_masked_colors_w2', 2, [3]),
        helper.make_tensor_value_info('masked_colors', 2, [1, 1, 3, 3]),
        helper.make_tensor_value_info('onehot_bool', 9, [1, 9, 3, 3]),
    ]
    return model('task218_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
