"""Task 079 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('chmask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPx+Faz8AAIA/')),
        tensor('lut', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE5LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAQEBAQMCAgACAwAC')),
        tensor('ohv', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
        tensor('roww', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArfhPZ3fG/8cjk/AW5RWQRpeIYHZCPHCl/KGw5a54QRVfkCFVCAlhhLAEAcRgAAIEEK1yM8rMUnNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('inv_lnb', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo7PRQ+')),
        tensor('Kf', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAADBB')),
        tensor('zero32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('bandsz', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAwAAAA4AAAA=')),
        tensor('axb', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('three', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('c10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGwAAAAAAAAAbAAAAAAAAAA==')),
        tensor('paxes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'chmask'], ['mcounts'], equation='bcrs,c->c'),
        helper.make_node('Cast', ['mcounts'], ['cidx'], to=6),
        helper.make_node('Gather', ['lut', 'cidx'], ['score'], axis=0),
        helper.make_node('ArgMax', ['score'], ['best_color'], axis=0, keepdims=1),
        helper.make_node('OneHot', ['best_color', 'c10', 'ohv'], ['mask'], axis=1),
        helper.make_node('Einsum', ['input', 'mask', 'roww'], ['rowS'], equation='bcrs,kc,r->b'),
        helper.make_node('Log', ['rowS'], ['rowL']),
        helper.make_node('Mul', ['rowL', 'inv_lnb'], ['rowLs']),
        helper.make_node('Floor', ['rowLs'], ['rowF']),
        helper.make_node('Sub', ['Kf', 'rowF'], ['r0f']),
        helper.make_node('Cast', ['r0f'], ['row'], to=6),
        helper.make_node('Cast', ['best_color'], ['color'], to=6),
        helper.make_node('Concat', ['color', 'row', 'zero32'], ['bstart'], axis=0),
        helper.make_node('Add', ['bstart', 'bandsz'], ['bend']),
        helper.make_node('Slice', ['input', 'bstart', 'bend', 'axb'], ['band']),
        helper.make_node('AveragePool', ['band'], ['col_scores'], kernel_shape=[3, 3], strides=[1, 1]),
        helper.make_node('ArgMax', ['col_scores'], ['col_arg'], axis=3, keepdims=0),
        helper.make_node('Cast', ['col_arg'], ['col_i'], to=6),
        helper.make_node('Reshape', ['col_i', 'one'], ['col']),
        helper.make_node('Add', ['col', 'three'], ['col_end']),
        helper.make_node('Slice', ['band', 'col', 'col_end', 'three'], ['winner_f']),
        helper.make_node('Cast', ['winner_f'], ['winner_b'], to=9),
        helper.make_node('Not', ['winner_b'], ['bg_b']),
        helper.make_node('Cast', ['mask'], ['mask_b'], to=9),
        helper.make_node('Slice', ['mask_b', 'one', 'c10', 'one'], ['mask9']),
        helper.make_node('Unsqueeze', ['mask9', 'paxes'], ['mask9r']),
        helper.make_node('And', ['winner_b', 'mask9r'], ['wblock']),
        helper.make_node('Concat', ['bg_b', 'wblock'], ['opatch'], axis=1),
        helper.make_node('Pad', ['opatch', 'pads', '', 'paxes'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('mcounts', 1, [10]),
        helper.make_tensor_value_info('cidx', 6, [10]),
        helper.make_tensor_value_info('score', 3, [10]),
        helper.make_tensor_value_info('best_color', 7, [1]),
        helper.make_tensor_value_info('mask', 1, [1, 10]),
        helper.make_tensor_value_info('rowS', 1, [1]),
        helper.make_tensor_value_info('rowL', 1, [1]),
        helper.make_tensor_value_info('rowLs', 1, [1]),
        helper.make_tensor_value_info('rowF', 1, [1]),
        helper.make_tensor_value_info('r0f', 1, [1]),
        helper.make_tensor_value_info('color', 6, [1]),
        helper.make_tensor_value_info('row', 6, [1]),
        helper.make_tensor_value_info('bstart', 6, [3]),
        helper.make_tensor_value_info('bend', 6, [3]),
        helper.make_tensor_value_info('band', 1, [1, 1, 3, 14]),
        helper.make_tensor_value_info('col_scores', 1, [1, 1, 1, 12]),
        helper.make_tensor_value_info('col_arg', 7, [1, 1, 1]),
        helper.make_tensor_value_info('col_i', 6, [1, 1, 1]),
        helper.make_tensor_value_info('col', 6, [1]),
        helper.make_tensor_value_info('col_end', 6, [1]),
        helper.make_tensor_value_info('winner_f', 1, [1, 1, 3, 3]),
        helper.make_tensor_value_info('winner_b', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('bg_b', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('mask_b', 9, [1, 10]),
        helper.make_tensor_value_info('mask9', 9, [1, 9]),
        helper.make_tensor_value_info('mask9r', 9, [1, 9, 1, 1]),
        helper.make_tensor_value_info('wblock', 9, [1, 9, 3, 3]),
        helper.make_tensor_value_info('opatch', 9, [1, 10, 3, 3]),
    ]
    return model('task079_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
