"""Task 189 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('vidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAA=')),
        tensor('hidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAAAAAAAAAAABgAAAAAAAAA=')),
        tensor('pst_t', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAAAAAA=')),
        tensor('pst_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('dpat', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAABgAAAAYAAAA=')),
        tensor('axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('qst_t', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAABwAAAAcAAAA=')),
        tensor('qst_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAA=')),
        tensor('dpal', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAgAAAAIAAAA=')),
        tensor('cvals', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDksIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEAAAIBAAACgQAAAwEAAAOBAAAAAQQAAEEE=')),
        tensor('rscales', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAQEAAAEBA')),
        tensor('zu8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('cids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('pad18_pads_17_14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAA==')),
        tensor('pad18_axes_17_15', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('GatherND', ['input', 'vidx'], ['fvf'], batch_dims=1),
        helper.make_node('GatherND', ['input', 'hidx'], ['fhf'], batch_dims=1),
        helper.make_node('Cast', ['fvf'], ['fv'], to=9),
        helper.make_node('Cast', ['fhf'], ['fh'], to=9),
        helper.make_node('Concat', ['fv', 'fv', 'fh'], ['cond3'], axis=0),
        helper.make_node('Where', ['cond3', 'pst_t', 'pst_f'], ['pat_st']),
        helper.make_node('Add', ['pat_st', 'dpat'], ['pat_en']),
        helper.make_node('Slice', ['input', 'pat_st', 'pat_en', 'axes'], ['pattern_f']),
        helper.make_node('Where', ['cond3', 'qst_t', 'qst_f'], ['pal_st']),
        helper.make_node('Add', ['pal_st', 'dpal'], ['pal_en']),
        helper.make_node('Slice', ['input', 'pal_st', 'pal_en', 'axes'], ['palette_f']),
        helper.make_node('Conv', ['palette_f', 'cvals'], ['palette_ids'], kernel_shape=[1, 1]),
        helper.make_node('Cast', ['palette_ids'], ['pids_u8'], to=2),
        helper.make_node('Resize', ['pids_u8', '', 'rscales'], ['palette_big'], coordinate_transformation_mode='asymmetric', mode='nearest', nearest_mode='floor'),
        helper.make_node('Cast', ['pattern_f'], ['pat_b'], to=9),
        helper.make_node('Where', ['pat_b', 'palette_big', 'zu8'], ['filled_ids']),
        helper.make_node('Equal', ['filled_ids', 'cids'], ['filled_bool']),
        helper.make_node('Pad', ['filled_bool', 'pad18_pads_17_14', '', 'pad18_axes_17_15'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('fvf', 1, [1]),
        helper.make_tensor_value_info('fhf', 1, [1]),
        helper.make_tensor_value_info('fv', 9, [1]),
        helper.make_tensor_value_info('fh', 9, [1]),
        helper.make_tensor_value_info('cond3', 9, [3]),
        helper.make_tensor_value_info('pat_st', 6, [3]),
        helper.make_tensor_value_info('pat_en', 6, [3]),
        helper.make_tensor_value_info('pattern_f', 1, [1, 1, 6, 6]),
        helper.make_tensor_value_info('pal_st', 6, [3]),
        helper.make_tensor_value_info('pal_en', 6, [3]),
        helper.make_tensor_value_info('palette_f', 1, [1, 9, 2, 2]),
        helper.make_tensor_value_info('palette_ids', 1, [1, 1, 2, 2]),
        helper.make_tensor_value_info('pids_u8', 2, [1, 1, 2, 2]),
        helper.make_tensor_value_info('palette_big', 2, [1, 1, 6, 6]),
        helper.make_tensor_value_info('pat_b', 9, [1, 1, 6, 6]),
        helper.make_tensor_value_info('filled_ids', 2, [1, 1, 6, 6]),
        helper.make_tensor_value_info('filled_bool', 9, [1, 10, 6, 6]),
    ]
    return model('task189_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
