"""Task 091 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAEAAAAAA')),
        tensor('rax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAA')),
        tensor('cax', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAA')),
        tensor('one8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('c30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoe')),
        tensor('ax23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('z1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('pax23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('decode', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBBAQEBAMEBAIE')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'weights'], ['codef'], kernel_shape=[1, 1], pads=[0, 0, -15, -15]),
        helper.make_node('Cast', ['codef'], ['code'], to=2),
        helper.make_node('ReduceMax', ['code', 'rax'], ['row_any'], keepdims=0),
        helper.make_node('ReduceMax', ['code', 'cax'], ['col_any'], keepdims=0),
        helper.make_node('ArgMax', ['row_any'], ['y0'], axis=1, keepdims=0),
        helper.make_node('ArgMax', ['row_any'], ['y1'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('ArgMax', ['col_any'], ['x0'], axis=1, keepdims=0),
        helper.make_node('ArgMax', ['col_any'], ['x1'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['y0'], ['y0i'], to=3),
        helper.make_node('Cast', ['y1'], ['y1i'], to=3),
        helper.make_node('Cast', ['x0'], ['x0i'], to=3),
        helper.make_node('Cast', ['x1'], ['x1i'], to=3),
        helper.make_node('Sub', ['y0i', 'one8'], ['y0m1']),
        helper.make_node('Concat', ['y0m1', 'x0i'], ['starts8'], axis=0),
        helper.make_node('Add', ['y1i', 'two8'], ['y1p2']),
        helper.make_node('Add', ['x1i', 'one8'], ['x1p1']),
        helper.make_node('Concat', ['y1p2', 'x1p1'], ['ends8'], axis=0),
        helper.make_node('Cast', ['starts8'], ['starts'], to=6),
        helper.make_node('Cast', ['ends8'], ['ends'], to=6),
        helper.make_node('Slice', ['code', 'starts', 'ends', 'ax23'], ['cropped']),
        helper.make_node('Sub', ['ends8', 'starts8'], ['wh']),
        helper.make_node('Sub', ['c30', 'wh'], ['pe8']),
        helper.make_node('Concat', ['z1', 'z1', 'pe8'], ['pads8'], axis=0),
        helper.make_node('Cast', ['pads8'], ['pads'], to=7),
        helper.make_node('Pad', ['cropped', 'pads', '', 'pax23'], ['label30'], mode='constant'),
        helper.make_node('Equal', ['label30', 'decode'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('cropped', 2, [1, 1, 1, 1]),
        helper.make_tensor_value_info('label30', 2, [1, 1, 30, 30]),
    ]
    return model('task091_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
