"""Task 335 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('S8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAA')),
        tensor('S2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('V', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAACAvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AAAAAA==')),
        tensor('T', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AAAAPwAAAD/NzMw9AACAPwAAgD8AAIA/AACAPw==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'S8', 'idx'], ['r8'], equation='bkrc,k,ar->b'),
        helper.make_node('Einsum', ['input', 'S2', 'idx'], ['r2'], equation='bkrc,k,ar->b'),
        helper.make_node('Einsum', ['input', 'S8', 'idx'], ['c8'], equation='bkrc,k,ac->b'),
        helper.make_node('Einsum', ['input', 'S2', 'idx'], ['c2'], equation='bkrc,k,ac->b'),
        helper.make_node('Min', ['r8', 'r2'], ['rmin']),
        helper.make_node('Max', ['r8', 'r2'], ['rmax']),
        helper.make_node('GreaterOrEqual', ['idx', 'rmin'], ['rge']),
        helper.make_node('LessOrEqual', ['idx', 'rmax'], ['rle']),
        helper.make_node('And', ['rge', 'rle'], ['ract']),
        helper.make_node('Equal', ['idx', 'r2'], ['req2']),
        helper.make_node('Not', ['req2'], ['rn2']),
        helper.make_node('Concat', ['ract', 'rn2'], ['R_b'], axis=0),
        helper.make_node('Cast', ['R_b'], ['R'], to=1),
        helper.make_node('Min', ['c8', 'c2'], ['cmin']),
        helper.make_node('Max', ['c8', 'c2'], ['cmax']),
        helper.make_node('GreaterOrEqual', ['idx', 'cmin'], ['cge']),
        helper.make_node('LessOrEqual', ['idx', 'cmax'], ['cle']),
        helper.make_node('And', ['cge', 'cle'], ['cact']),
        helper.make_node('Equal', ['idx', 'c8'], ['ceq8']),
        helper.make_node('Not', ['ceq8'], ['cn8']),
        helper.make_node('Concat', ['cact', 'cn8'], ['C_b'], axis=0),
        helper.make_node('Cast', ['C_b'], ['C'], to=1),
        helper.make_node('Einsum', ['input', 'V', 'V', 'T', 'R', 'C'], ['output'], equation='blrc,pl,pk,pfg,fr,gc->bkrc'),
    ]
    value_infos = [
    ]
    return model('task335_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
