"""Task 057 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('channel_ids_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('offsets3_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAA=')),
        tensor('bg_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('bg_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAACAAAAAAAAAAHAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABgAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'bg_starts', 'bg_ends'], ['bg_f']),
        helper.make_node('Cast', ['bg_f'], ['bg'], to=2),
        helper.make_node('ReduceMin', ['bg'], ['row_has'], axes=[0, 1, 3], keepdims=0),
        helper.make_node('ReduceMin', ['bg'], ['col_has'], axes=[0, 1, 2], keepdims=0),
        helper.make_node('ArgMin', ['row_has'], ['top_i64'], axis=0, keepdims=0, select_last_index=0),
        helper.make_node('ArgMin', ['col_has'], ['left_i64'], axis=0, keepdims=0, select_last_index=0),
        helper.make_node('Cast', ['top_i64'], ['top'], to=6),
        helper.make_node('Cast', ['left_i64'], ['left'], to=6),
        helper.make_node('Add', ['top', 'offsets3_i32'], ['row_idx']),
        helper.make_node('Add', ['left', 'offsets3_i32'], ['col_idx']),
        helper.make_node('Gather', ['bg', 'row_idx'], ['bg_rows'], axis=2),
        helper.make_node('Gather', ['bg_rows', 'col_idx'], ['bg_patch'], axis=3),
        helper.make_node('Equal', ['bg_patch', 'zero_u8'], ['fgmask3']),
        helper.make_node('ReduceMax', ['input'], ['color_all'], axes=[0, 2, 3], keepdims=0),
        helper.make_node('ArgMax', ['color_all'], ['color_i64'], axis=0, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['color_i64'], ['color_u8'], to=2),
        helper.make_node('Where', ['fgmask3', 'color_u8', 'zero_u8'], ['label3']),
        helper.make_node('Concat', ['label3', 'label3'], ['label_dup'], axis=3),
        helper.make_node('Equal', ['label_dup', 'channel_ids_u8'], ['patch']),
        helper.make_node('Pad', ['patch', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task057_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
