"""Task 073 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('B', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAY6nQwAAAAAAAAAAAAAAAANbXKkAAAAAAAAAAAAAAAAAAAAAA3Lc5wIbac0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('K', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArePIE7z6qoPPcliL63wB49')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'input', 'input', 'B', 'B', 'B', 'B', 'K'], ['output'], equation='njab,ncas,ndub,pj,qc,qd,po,pq->noab'),
    ]
    value_infos = [
    ]
    return model('task073_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
