"""Task 269 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('crop_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAA')),
        tensor('crop_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAMAAAAAAAAA')),
        tensor('crop_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pad_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('ch0_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('nine_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqASA==')),
        tensor('roi_const_f32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApD0hpB')),
        tensor('roi_prefix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDYsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAACAPwAAgD8=')),
        tensor('unsq_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('out_sizes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAoAAAAAAAAAHgAAAAAAAAAeAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'crop_starts', 'crop_ends', 'crop_axes'], ['crop']),
        helper.make_node('Cast', ['crop'], ['crop_u8'], to=2),
        helper.make_node('Pad', ['crop_u8', 'pad_pads', '', 'crop_axes'], ['src4'], mode='constant'),
        helper.make_node('Gather', ['crop_u8', 'ch0_idx'], ['ch0_u8'], axis=1),
        helper.make_node('Cast', ['ch0_u8'], ['ch0_f16'], to=10),
        helper.make_node('ReduceSum', ['ch0_f16'], ['black_count_f16'], keepdims=0),
        helper.make_node('Sub', ['nine_f16', 'black_count_f16'], ['scale_f16']),
        helper.make_node('Cast', ['scale_f16'], ['scale_f32'], to=1),
        helper.make_node('Div', ['roi_const_f32', 'scale_f32'], ['roi_end']),
        helper.make_node('Unsqueeze', ['roi_end', 'unsq_axes'], ['roi_end_vec']),
        helper.make_node('Concat', ['roi_prefix', 'roi_end_vec', 'roi_end_vec'], ['roi'], axis=0),
        helper.make_node('Resize', ['src4', 'roi', '', 'out_sizes'], ['output'], coordinate_transformation_mode='tf_crop_and_resize', extrapolation_value=0.0, mode='nearest', nearest_mode='floor'),
    ]
    value_infos = [
        helper.make_tensor_value_info('crop', 1, [1, 10, 3, 3]),
        helper.make_tensor_value_info('crop_u8', 2, [1, 10, 3, 3]),
        helper.make_tensor_value_info('src4', 2, [1, 10, 4, 4]),
        helper.make_tensor_value_info('ch0_u8', 2, [1, 3, 3]),
        helper.make_tensor_value_info('ch0_f16', 10, [1, 3, 3]),
        helper.make_tensor_value_info('black_count_f16', 10, []),
        helper.make_tensor_value_info('scale_f16', 10, []),
        helper.make_tensor_value_info('scale_f32', 1, []),
        helper.make_tensor_value_info('roi_end', 1, []),
        helper.make_tensor_value_info('roi_end_vec', 1, [1]),
        helper.make_tensor_value_info('roi', 1, [8]),
    ]
    return model('task269_live_exact', nodes, inits, output_dtype=2, opset=18, value_infos=value_infos)
