"""Task 087 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('rois', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAFBAAABQQAAA/sEAAP7B')),
        tensor('batch_indices', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('RoiAlign', ['input', 'rois', 'batch_indices'], ['output'], coordinate_transformation_mode='half_pixel', mode='avg', output_height=30, output_width=30, sampling_ratio=1, spatial_scale=1.0),
    ]
    value_infos = [
    ]
    return model('task087_live_exact', nodes, inits, output_dtype=1, opset=16, value_infos=value_infos)
