"""Task 400 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('occ_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('c900', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqEAwAA')),
        tensor('cW', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAA')),
        tensor('cgs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoXAAAA')),
        tensor('axes2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('steps2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr//////////w==')),
        tensor('off35', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAojAAAA')),
    ]
    nodes = [
        helper.make_node('MaxPool', ['input'], ['mpv', 'mpi'], kernel_shape=[30, 30], strides=[30, 30]),
        helper.make_node('Gather', ['mpi', 'occ_i'], ['mpi__i32'], axis=1),
        helper.make_node('Cast', ['mpi__i32'], ['oi4'], to=6),
        helper.make_node('Reshape', ['oi4', 'occ_i'], ['oi']),
        helper.make_node('Mod', ['oi', 'c900'], ['loc']),
        helper.make_node('Div', ['loc', 'cW'], ['row']),
        helper.make_node('Mod', ['loc', 'cW'], ['col']),
        helper.make_node('Sub', ['cgs', 'row'], ['arow']),
        helper.make_node('Sub', ['cgs', 'col'], ['acol']),
        helper.make_node('Concat', ['arow', 'acol'], ['starts2'], axis=0),
        helper.make_node('Sub', ['starts2', 'off35'], ['ends2']),
        helper.make_node('Slice', ['input', 'starts2', 'ends2', 'axes2', 'steps2'], ['patch']),
        helper.make_node('Pad', ['patch'], ['output'], pads=[0, 0, 0, 0, 0, 0, 25, 25]),
    ]
    value_infos = [
        helper.make_tensor_value_info('patch', 1, [1, 10, 5, 5]),
    ]
    return model('task400_live_exact', nodes, inits, output_dtype=1, opset=10, value_infos=value_infos)
