"""Task 047 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('reduce_rows_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('reduce_cols_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('false_1x1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('tail_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAABUAAAAAAAAA')),
        tensor('row_other_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoV')),
        tensor('row_orange_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAom')),
        tensor('row_cyan_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApY')),
        tensor('col_other_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoL')),
        tensor('col_orange_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApG')),
        tensor('col_cyan_code', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo4')),
        tensor('channel_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAGAAAAAABhgA')),
        tensor('slice_start_7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoHAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('slice_end_7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAgAAAAAAAAABwAAAAAAAAA=')),
        tensor('slice_start_8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('slice_end_8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAAcAAAAAAAAABwAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_start_7', 'slice_end_7', 'slice_axes'], ['ch7']),
        helper.make_node('Cast', ['ch7'], ['ch7_b'], to=9),
        helper.make_node('ReduceMax', ['ch7_b', 'reduce_cols_axis'], ['row7_b'], keepdims=1),
        helper.make_node('ReduceMax', ['ch7_b', 'reduce_rows_axis'], ['col7_b'], keepdims=1),
        helper.make_node('Slice', ['input', 'slice_start_8', 'slice_end_8', 'slice_axes'], ['ch8']),
        helper.make_node('Cast', ['ch8'], ['ch8_b'], to=9),
        helper.make_node('ReduceMax', ['ch8_b', 'reduce_cols_axis'], ['row8_b'], keepdims=1),
        helper.make_node('ReduceMax', ['ch8_b', 'reduce_rows_axis'], ['col8_b'], keepdims=1),
        helper.make_node('Concat', ['row8_b', 'false_1x1'], ['row8_padded'], axis=2),
        helper.make_node('Where', ['row7_b', 'row_orange_code', 'row_other_code'], ['row_bits_after_orange']),
        helper.make_node('Where', ['row8_padded', 'row_cyan_code', 'row_bits_after_orange'], ['row_bits_1_to_7']),
        helper.make_node('Concat', ['row_other_code', 'row_bits_1_to_7', 'row_other_code'], ['row_bits_9'], axis=2),
        helper.make_node('Pad', ['row_bits_9', 'tail_pads', '', 'reduce_rows_axis'], ['row_bits_30'], mode='constant'),
        helper.make_node('Where', ['col7_b', 'col_orange_code', 'col_other_code'], ['col_code_after_orange']),
        helper.make_node('Where', ['col8_b', 'col_cyan_code', 'col_code_after_orange'], ['col_code_1_to_6']),
        helper.make_node('Concat', ['col_other_code', 'col_code_1_to_6', 'col_other_code', 'col_other_code'], ['col_code_9'], axis=3),
        helper.make_node('Pad', ['col_code_9', 'tail_pads', '', 'reduce_cols_axis'], ['col_code_30'], mode='constant'),
        helper.make_node('BitwiseAnd', ['col_code_30', 'channel_mask'], ['col_bits_30']),
        helper.make_node('BitwiseAnd', ['row_bits_30', 'col_bits_30'], ['output']),
    ]
    value_infos = [
    ]
    return model('task047_live_exact', nodes, inits, output_dtype=2, opset=20, value_infos=value_infos)
