"""Task 010 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('k', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAzMCwgMSksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwj///////////////////////////8IBwYFBAMCAQD///////////////////////////8IBwYFBAMCAQD///////////////////////////8IBwYFBAMCAQD///////////////////////////8IBwYFBAMCAQD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8=')),
        tensor('sel5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAA')),
        tensor('e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDQsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQg==')),
        tensor('zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('zc4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDQsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('nine1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJ')),
        tensor('ninef', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqASA==')),
        tensor('jpads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAABUAAAAAAAAA')),
        tensor('s1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('s9', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAA==')),
        tensor('s2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'sel5'], ['H30'], equation='bchw,c->bw'),
        helper.make_node('Slice', ['H30', 's1', 's9', 's1', 's2'], ['H4']),
        helper.make_node('Cast', ['H4'], ['H4c'], to=2),
        helper.make_node('Unsqueeze', ['H4c'], ['n'], axes=[1]),
        helper.make_node('Unsqueeze', ['n'], ['p'], axes=[3]),
        helper.make_node('Greater', ['n', 'p'], ['q']),
        helper.make_node('Cast', ['q'], ['rf'], to=10),
        helper.make_node('ReduceSum', ['rf'], ['s'], axes=[3], keepdims=0),
        helper.make_node('Equal', ['e', 's'], ['tt']),
        helper.make_node('Where', ['tt', 'n', 'zero'], ['u']),
        helper.make_node('Split', ['u'], ['u0', 'u1', 'u2', 'u3'], axis=3, split=[1, 1, 1, 1]),
        helper.make_node('Concat', ['zc4', 'u0', 'zc4', 'u1', 'zc4', 'u2', 'zc4', 'u3', 'zc4'], ['B'], axis=3),
        helper.make_node('Cast', ['n'], ['nf'], to=10),
        helper.make_node('Sub', ['ninef', 'nf'], ['bgf']),
        helper.make_node('Cast', ['bgf'], ['bg'], to=2),
        helper.make_node('Unsqueeze', ['bg'], ['w'], axes=[2]),
        helper.make_node('Split', ['w'], ['w0', 'w1', 'w2', 'w3'], axis=3, split=[1, 1, 1, 1]),
        helper.make_node('Concat', ['nine1', 'w0', 'nine1', 'w1', 'nine1', 'w2', 'nine1', 'w3', 'nine1'], ['G'], axis=3),
        helper.make_node('Concat', ['G', 'B'], ['H'], axis=1),
        helper.make_node('Pad', ['H', 'jpads'], ['I'], mode='constant'),
        helper.make_node('Less', ['k', 'I'], ['output']),
    ]
    value_infos = [
    ]
    return model('task010_live_exact', nodes, inits, output_dtype=9, opset=12, value_infos=value_infos)
