"""Task 188 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('coef', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo2DY8+zMX3PvMENT/XCDA/0ZNWv2g5bb/q8YC/VoKKv+Zpk78OxJu/daajv+oiq79XSLK/bSO5v1uev79o48W/4frLv9Xq0b+4uNe/6mjdvxv/4r9ffui/SuntvwpC879yivi/BcT9vwV4AcDMBwTA0JEGwHoWCcCmybI+rtUaP/MENb//f3a/PReGvzA+lL80KKG/RhytvyRJuL8e08K/MdLMv0pa1r9qet+/iD7ovzix8L+M2vi/v2AAwAA2BMCc7wfAxY8LwDoYD8ARixLAmukVwC81GcD6bhzAF5gfwH6xIsANvCXAmbgowNSnK8A=')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input'], ['area'], equation='nkhw->n'),
        helper.make_node('Einsum', ['input', 'coef', 'coef'], ['w_s'], equation='nkhw,pw,pw->n'),
        helper.make_node('Einsum', ['input', 'coef', 'coef'], ['h_s'], equation='nkhw,ph,ph->n'),
        helper.make_node('Greater', ['w_s', 'h_s'], ['w_gt_h']),
        helper.make_node('Equal', ['w_s', 'h_s'], ['is_square']),
        helper.make_node('Einsum', ['input', 'input', 'coef'], ['v_match'], equation='nkhw,nkzw,ph->n'),
        helper.make_node('Less', ['v_match', 'h_s'], ['h_content']),
        helper.make_node('And', ['is_square', 'h_content'], ['square_h']),
        helper.make_node('Or', ['w_gt_h', 'square_h'], ['is_h']),
        helper.make_node('Add', ['h_s', 'h_s'], ['h2_s']),
        helper.make_node('Add', ['w_s', 'w_s'], ['w2_s']),
        helper.make_node('Where', ['is_h', 'h2_s', 'h_s'], ['row_dim_s']),
        helper.make_node('Where', ['is_h', 'w_s', 'w2_s'], ['col_dim_s']),
        helper.make_node('Concat', ['row_dim_s', 'area'], ['row_feat'], axis=0),
        helper.make_node('Concat', ['col_dim_s', 'area'], ['col_feat'], axis=0),
        helper.make_node('Einsum', ['input', 'row_feat', 'coef', 'col_feat', 'coef'], ['output'], equation='nkhw,p,ph,q,qw->nkhw'),
    ]
    value_infos = [
    ]
    return model('task188_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
