"""Task 184 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('channel_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('ones30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
        tensor('row_diff_q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/AQ==')),
        tensor('col_diff_q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/AQ==')),
        tensor('row_prefix_q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('col_prefix_q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('x_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('w_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('group_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgM=')),
        tensor('group_ids_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgM=')),
        tensor('pad18_pads_15_12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGwAAAAAAAAAbAAAAAAAAAA==')),
        tensor('pad18_axes_15_13', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'channel_mask', 'ones30'], ['row_count'], equation='nchw,ac,bw->nahb'),
        helper.make_node('Sign', ['row_count'], ['row_nonempty']),
        helper.make_node('Cast', ['row_nonempty'], ['row_u8'], to=2),
        helper.make_node('QLinearConv', ['row_u8', 'q_scale', 'x_zero', 'row_diff_q', 'q_scale', 'w_zero', 'q_scale', 'x_zero'], ['row_start'], kernel_shape=[2, 1], pads=[1, 0, 0, 0]),
        helper.make_node('QLinearConv', ['row_start', 'q_scale', 'x_zero', 'row_prefix_q', 'q_scale', 'x_zero', 'q_scale', 'x_zero'], ['row_group'], kernel_shape=[30, 1], pads=[29, 0, 0, 0]),
        helper.make_node('Einsum', ['input', 'channel_mask', 'ones30'], ['col_count'], equation='nchw,ac,bh->nabw'),
        helper.make_node('Sign', ['col_count'], ['col_nonempty']),
        helper.make_node('Cast', ['col_nonempty'], ['col_u8'], to=2),
        helper.make_node('QLinearConv', ['col_u8', 'q_scale', 'x_zero', 'col_diff_q', 'q_scale', 'w_zero', 'q_scale', 'x_zero'], ['col_start'], kernel_shape=[1, 2], pads=[0, 1, 0, 0]),
        helper.make_node('QLinearConv', ['col_start', 'q_scale', 'x_zero', 'col_prefix_q', 'q_scale', 'x_zero', 'q_scale', 'x_zero'], ['col_group'], kernel_shape=[1, 30], pads=[0, 29, 0, 0]),
        helper.make_node('Equal', ['col_group', 'group_ids_col'], ['col_onehot_bool']),
        helper.make_node('Cast', ['col_onehot_bool'], ['col_onehot'], to=1),
        helper.make_node('Equal', ['row_group', 'group_ids'], ['row_onehot_bool']),
        helper.make_node('Cast', ['row_onehot_bool'], ['row_onehot'], to=1),
        helper.make_node('Einsum', ['input', 'channel_mask', 'row_onehot', 'col_onehot'], ['counts_row_col'], equation='nchw,ac,nahr,nakw->ncrk'),
        helper.make_node('Pad', ['counts_row_col', 'pad18_pads_15_12', '', 'pad18_axes_15_13'], ['output']),
    ]
    value_infos = [
    ]
    return model('task184_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
