"""Task 136 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('idx1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('idx2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('off_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAog')),
        tensor('thirty_u16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPHUyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAA==')),
        tensor('thirty_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoe')),
        tensor('row_positions_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('col_positions_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('pad_config', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('row1_invalid_off__zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
    ]
    nodes = [
        helper.make_node('MaxPool', ['input'], ['channel_max', 'channel_idx_i64'], kernel_shape=[30, 30], storage_order=0),
        helper.make_node('Gather', ['channel_idx_i64', 'idx1'], ['idx1_i64'], axis=1),
        helper.make_node('Gather', ['channel_idx_i64', 'idx2'], ['idx2_i64'], axis=1),
        helper.make_node('Cast', ['idx1_i64'], ['idx1_u16'], to=4),
        helper.make_node('Div', ['idx1_u16', 'thirty_u16'], ['row1_abs_u16']),
        helper.make_node('Mod', ['idx1_u16', 'thirty_u16'], ['col1_u16'], fmod=0),
        helper.make_node('Cast', ['row1_abs_u16'], ['row1_abs_u8'], to=2),
        helper.make_node('Sub', ['row1_abs_u8', 'thirty_u8'], ['row1']),
        helper.make_node('Cast', ['col1_u16'], ['col1'], to=2),
        helper.make_node('Cast', ['idx2_i64'], ['idx2_u16'], to=4),
        helper.make_node('Div', ['idx2_u16', 'thirty_u16'], ['row2_abs_u16']),
        helper.make_node('Mod', ['idx2_u16', 'thirty_u16'], ['col2_u16'], fmod=0),
        helper.make_node('Cast', ['row2_abs_u16'], ['row2_abs_u8'], to=2),
        helper.make_node('Sub', ['row2_abs_u8', 'thirty_u8'], ['row2_minus30']),
        helper.make_node('Sub', ['row2_minus30', 'thirty_u8'], ['row2']),
        helper.make_node('Cast', ['col2_u16'], ['col2'], to=2),
        helper.make_node('Add', ['row1', 'one_u8'], ['row1_next']),
        helper.make_node('Sub', ['row1', 'col1'], ['diag1_id']),
        helper.make_node('Greater', ['row_positions_u8', 'row1_next'], ['row1_gt_next']),
        helper.make_node('Less', ['row_positions_u8', 'row1'], ['row1_lt']),
        helper.make_node('Equal', ['row1_lt', 'row1_gt_next'], ['row1_block']),
        helper.make_node('Sub', ['row_positions_u8', 'diag1_id'], ['diag1_cols']),
        helper.make_node('Where', ['row1_gt_next', 'off_u8', 'row1_invalid_off__zero'], ['row1_invalid_off']),
        helper.make_node('Add', ['diag1_cols', 'row1_invalid_off'], ['diag1_masked_cols']),
        helper.make_node('Cast', ['row1_block'], ['row1_block_u8'], to=2),
        helper.make_node('Sub', ['col1', 'diag1_masked_cols'], ['left1_delta']),
        helper.make_node('Mul', ['row1_block_u8', 'left1_delta'], ['left1_fix']),
        helper.make_node('Add', ['diag1_masked_cols', 'left1_fix'], ['left1']),
        helper.make_node('Sub', ['col_positions_u8', 'left1'], ['diff1']),
        helper.make_node('LessOrEqual', ['diff1', 'row1_block_u8'], ['out1']),
        helper.make_node('Add', ['row2', 'one_u8'], ['row2_next']),
        helper.make_node('Sub', ['row2', 'col2'], ['diag2_id']),
        helper.make_node('Greater', ['row_positions_u8', 'row2_next'], ['row2_gt_next']),
        helper.make_node('Less', ['row_positions_u8', 'row2'], ['row2_lt']),
        helper.make_node('Equal', ['row2_lt', 'row2_gt_next'], ['row2_block']),
        helper.make_node('Sub', ['row_positions_u8', 'diag2_id'], ['diag2_cols']),
        helper.make_node('Where', ['row2_lt', 'off_u8', 'row1_invalid_off__zero'], ['row2_invalid_off']),
        helper.make_node('Add', ['diag2_cols', 'row2_invalid_off'], ['diag2_masked_cols']),
        helper.make_node('Cast', ['row2_block'], ['row2_block_u8'], to=2),
        helper.make_node('Sub', ['col2', 'diag2_masked_cols'], ['left2_delta']),
        helper.make_node('Mul', ['row2_block_u8', 'left2_delta'], ['left2_fix']),
        helper.make_node('Add', ['diag2_masked_cols', 'left2_fix'], ['left2']),
        helper.make_node('Sub', ['col_positions_u8', 'left2'], ['diff2']),
        helper.make_node('LessOrEqual', ['diff2', 'row2_block_u8'], ['out2']),
        helper.make_node('Equal', ['out1', 'out2'], ['out0']),
        helper.make_node('Concat', ['out0', 'out1', 'out2'], ['grid3'], axis=1),
        helper.make_node('Pad', ['grid3', 'pad_config'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task136_live_exact', nodes, inits, output_dtype=9, opset=19, value_infos=value_infos)
