"""Task 354 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('Wcol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('gs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAA==')),
        tensor('ge', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('zu8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('s255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('zrow', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
        tensor('padsO', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('color', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'gs', 'ge'], ['grayf']),
        helper.make_node('Cast', ['grayf'], ['allow'], to=9),
        helper.make_node('Conv', ['input', 'Wcol'], ['row0F'], kernel_shape=[1, 1], pads=[0, 0, -29, -20]),
        helper.make_node('Cast', ['row0F'], ['vcol'], to=2),
        helper.make_node('Where', ['allow', 'vcol', 'zu8'], ['seed0']),
        helper.make_node('MaxPool', ['seed0'], ['p0'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Where', ['allow', 'p0', 'zu8'], ['g0']),
        helper.make_node('MaxPool', ['g0'], ['p1'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Where', ['allow', 'p1', 'zu8'], ['g1']),
        helper.make_node('MaxPool', ['g1'], ['p2'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Where', ['allow', 'p2', 'zu8'], ['g2']),
        helper.make_node('MaxPool', ['g2'], ['p3'], kernel_shape=[1, 3], pads=[0, 1, 0, 1], strides=[1, 1]),
        helper.make_node('Where', ['allow', 'p3', 'zu8'], ['g3']),
        helper.make_node('Concat', ['vcol', 'zrow', 'g3'], ['O10'], axis=2),
        helper.make_node('Pad', ['O10', 'padsO', 's255'], ['Opad'], mode='constant'),
        helper.make_node('Equal', ['Opad', 'color'], ['output']),
    ]
    value_infos = [
    ]
    return model('task354_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
