"""Task 221 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('c0_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('c0_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAA=')),
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('row_vec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBA')),
        tensor('col_vec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBA')),
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('nine_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAABBB')),
        tensor('channel0_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('two_channel0_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('motif_true', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQE=')),
        tensor('row_block_map', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCA3KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('row_cell_map', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'c0_starts', 'c0_ends', 'slice_axes'], ['c0_3x3']),
        helper.make_node('ReduceSum', ['c0_3x3'], ['voids_f'], axes=[0, 1, 2, 3], keepdims=0),
        helper.make_node('Sub', ['nine_f', 'voids_f'], ['filled_blocks_f']),
        helper.make_node('Div', ['filled_blocks_f', 'voids_f'], ['full_rows_div']),
        helper.make_node('Floor', ['full_rows_div'], ['full_rows_f']),
        helper.make_node('Mul', ['full_rows_f', 'voids_f'], ['full_rows_span']),
        helper.make_node('Sub', ['filled_blocks_f', 'full_rows_span'], ['remainder_f']),
        helper.make_node('Less', ['row_vec', 'voids_f'], ['row_in']),
        helper.make_node('Less', ['col_vec', 'voids_f'], ['col_in']),
        helper.make_node('Less', ['row_vec', 'full_rows_f'], ['full_rows']),
        helper.make_node('Equal', ['row_vec', 'full_rows_f'], ['at_partial_row']),
        helper.make_node('Less', ['col_vec', 'remainder_f'], ['partial_cols']),
        helper.make_node('Concat', ['row_in', 'full_rows', 'at_partial_row'], ['row_cond'], axis=1),
        helper.make_node('Cast', ['row_cond'], ['row_terms'], to=10),
        helper.make_node('Concat', ['col_in', 'col_in', 'partial_cols'], ['col_cond'], axis=1),
        helper.make_node('Cast', ['col_cond'], ['col_terms'], to=10),
        helper.make_node('Equal', ['c0_3x3', 'zero_f'], ['fg_cell_3']),
        helper.make_node('Concat', ['motif_true', 'fg_cell_3', 'fg_cell_3'], ['motif_cond'], axis=1),
        helper.make_node('Cast', ['motif_cond'], ['motif_terms'], to=10),
        helper.make_node('ReduceMax', ['input'], ['color_vec_f'], axes=[2, 3], keepdims=1),
        helper.make_node('Cast', ['color_vec_f'], ['color_vec_f16'], to=10),
        helper.make_node('Sub', ['color_vec_f16', 'two_channel0_selector'], ['delta_term']),
        helper.make_node('Concat', ['channel0_selector', 'delta_term', 'delta_term'], ['selector_terms'], axis=1),
        helper.make_node('Einsum', ['selector_terms', 'row_terms', 'col_terms', 'motif_terms', 'row_block_map', 'row_cell_map', 'row_block_map', 'row_cell_map'], ['output'], equation='ntcuv,ntax,ntyq,ntde,ra,rd,sq,se->ncrs'),
    ]
    value_infos = [
        helper.make_tensor_value_info('c0_3x3', 1, [1, 1, 3, 3]),
        helper.make_tensor_value_info('voids_f', 1, []),
        helper.make_tensor_value_info('filled_blocks_f', 1, []),
        helper.make_tensor_value_info('full_rows_div', 1, []),
        helper.make_tensor_value_info('full_rows_f', 1, []),
        helper.make_tensor_value_info('full_rows_span', 1, []),
        helper.make_tensor_value_info('remainder_f', 1, []),
        helper.make_tensor_value_info('row_in', 9, [1, 1, 7, 1]),
        helper.make_tensor_value_info('col_in', 9, [1, 1, 1, 7]),
        helper.make_tensor_value_info('full_rows', 9, [1, 1, 7, 1]),
        helper.make_tensor_value_info('at_partial_row', 9, [1, 1, 7, 1]),
        helper.make_tensor_value_info('partial_cols', 9, [1, 1, 1, 7]),
        helper.make_tensor_value_info('row_cond', 9, [1, 3, 7, 1]),
        helper.make_tensor_value_info('row_terms', 10, [1, 3, 7, 1]),
        helper.make_tensor_value_info('col_cond', 9, [1, 3, 1, 7]),
        helper.make_tensor_value_info('col_terms', 10, [1, 3, 1, 7]),
        helper.make_tensor_value_info('fg_cell_3', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('motif_cond', 9, [1, 3, 3, 3]),
        helper.make_tensor_value_info('motif_terms', 10, [1, 3, 3, 3]),
        helper.make_tensor_value_info('color_vec_f', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('color_vec_f16', 10, [1, 10, 1, 1]),
        helper.make_tensor_value_info('delta_term', 10, [1, 1, 10, 1, 1]),
        helper.make_tensor_value_info('selector_terms', 10, [1, 3, 10, 1, 1]),
    ]
    return model('task221_live_exact', nodes, inits, output_dtype=10, opset=12, value_infos=value_infos)
