"""Task 395 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('top_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('top_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAAMAAAAAAAAAAwAAAAAAAAA=')),
        tensor('bottom_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAA=')),
        tensor('bottom_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAYAAAAAAAAAAwAAAAAAAAA=')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDYsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAABsAAAAAAAAAGwAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'top_starts', 'top_ends', 'axes'], ['top_f']),
        helper.make_node('Slice', ['input', 'bottom_starts', 'bottom_ends', 'axes'], ['bottom_f']),
        helper.make_node('Cast', ['top_f'], ['top'], to=9),
        helper.make_node('Cast', ['bottom_f'], ['bottom'], to=9),
        helper.make_node('Or', ['top', 'bottom'], ['occupied']),
        helper.make_node('Not', ['occupied'], ['hole']),
        helper.make_node('And', ['occupied', 'hole'], ['zero']),
        helper.make_node('Concat', ['occupied', 'zero', 'hole'], ['small'], axis=1),
        helper.make_node('Pad', ['small', 'pads', '', 'axes'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task395_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
