"""Task 128 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('rs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqdUQE/kS0GPmUn3L3vVbo+IUaHPkDJj77qu8+/v8DiPw98Sz4SFsW8DHXkv2+C2j8KFqK9XdudvxtYC8Bl9Z0/8AoBvoL73b6xINW/XgV7P82VS76fvKy/FQQBwNrlwT7R3Rq+YE6wvyhlBMB0e8I+Q76nPoRWsL+JoMC/AAJavwDNYr8c+e0/NZo7wMNFQ8AlkII/f/O9PtAarr5RpE7ACcPOP5JUkD+pJRY9RG4kwDeheEAu3XS+/5IbQDtCPb8xrotAXjwfvvNHHEAmXas/uF6JPpOukj+pO0g+G0dlQEyqQr/dg5lAqshYvpUvs70AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('core', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqZ8OK+i0bRvp4H/L/Tkem/PmIjwMsV9r8QcCVAYdK8P/Gi378sMny/prgNvnec5b9iTRhATgLPP7AkRUC0nV/A')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'rs', 'core', 'rs'], ['output'], equation='bchw,hi,ij,rj->bcrw'),
    ]
    value_infos = [
    ]
    return model('task128_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
