"""Task 283 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('enc_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('q_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAzLCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAD/Av8C+AL/Av8A/wD/Af8A/wAAAAAAAAAAAAAC/QL9Af0C/QIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('q_b', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA/P////7///8AAAAA/f///wAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('q_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'enc_w'], ['enc_f'], dilations=[20, 20], strides=[1, 1]),
        helper.make_node('Cast', ['enc_f'], ['enc_i8'], to=3),
        helper.make_node('QLinearConv', ['enc_i8', 'q_scale', 'q_zero', 'q_w', 'q_scale', 'q_zero', 'q_scale', 'q_zero', 'q_b'], ['output'], kernel_shape=[3, 3], pads=[1, 1, 21, 21], strides=[1, 1]),
    ]
    value_infos = [
        helper.make_tensor_value_info('enc_f', 1, [1, 1, 10, 10]),
        helper.make_tensor_value_info('enc_i8', 3, [1, 1, 10, 10]),
    ]
    return model('task283_live_exact', nodes, inits, output_dtype=3, opset=13, value_infos=value_infos)
