"""Task 217 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('crop_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9//////////r/////////+v/////////')),
        tensor('shape_out', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAACQAAAAAAAAAJAAAAAAAAAA==')),
        tensor('pad_30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVAAAAAAAAABUAAAAAAAAA')),
        tensor('eight_half', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAhB')),
        tensor('mod3_kernel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
        tensor('zero1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('bg10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceMax', ['input'], ['color10'], axes=[2, 3], keepdims=1),
        helper.make_node('Cast', ['color10'], ['color10_u8'], to=2),
        helper.make_node('Equal', ['color10_u8', 'bg10'], ['is_bg_color']),
        helper.make_node('Where', ['is_bg_color', 'zero1', 'color10_u8'], ['fg10']),
        helper.make_node('Pad', ['input', 'crop_pads'], ['bg9'], mode='constant'),
        helper.make_node('Conv', ['bg9', 'mod3_kernel'], ['mod3_sums'], dilations=[3, 3]),
        helper.make_node('Less', ['mod3_sums', 'eight_half'], ['motif']),
        helper.make_node('Unsqueeze', ['motif'], ['left'], axes=[3, 5]),
        helper.make_node('Unsqueeze', ['motif'], ['right'], axes=[2, 4]),
        helper.make_node('And', ['left', 'right'], ['mask_out6']),
        helper.make_node('Reshape', ['mask_out6', 'shape_out'], ['mask_out_b']),
        helper.make_node('Where', ['mask_out_b', 'fg10', 'bg10'], ['crop10']),
        helper.make_node('Pad', ['crop10', 'pad_30'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task217_live_exact', nodes, inits, output_dtype=2, opset=11, value_infos=value_infos)
