"""Task 358 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('wgrid', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK1yM8AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('kvec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('ones_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('ones_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQEBAQEBAQEBAQEBAQEBAQE=')),
        tensor('qs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('qz', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('t_in', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('t_sel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABA')),
        tensor('t_p4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGBA')),
        tensor('chans', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkK')),
        tensor('sh4row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAeAAAAAAAAAA==')),
        tensor('sh4col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAHgAAAAAAAAABAAAAAAAAAA==')),
        tensor('shRow', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAB4AAAAAAAAA')),
        tensor('shCol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAAEAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'wgrid'], ['crow'], equation='nkrc,k->rn'),
        helper.make_node('Einsum', ['input', 'wgrid'], ['ccol'], equation='nkrc,k->nc'),
        helper.make_node('Greater', ['crow', 't_in'], ['rowin_b']),
        helper.make_node('Greater', ['ccol', 't_in'], ['colin_b']),
        helper.make_node('Greater', ['crow', 't_sel'], ['rowsel_b']),
        helper.make_node('Greater', ['ccol', 't_sel'], ['colsel_b']),
        helper.make_node('Xor', ['rowin_b', 'rowsel_b'], ['ra_b']),
        helper.make_node('ReduceMax', ['crow'], ['pmax'], keepdims=0),
        helper.make_node('Greater', ['pmax', 't_p4'], ['p4']),
        helper.make_node('Cast', ['rowsel_b'], ['rowsel_f'], to=1),
        helper.make_node('Cast', ['colsel_b'], ['colsel_f'], to=1),
        helper.make_node('Einsum', ['input', 'rowsel_f', 'kvec'], ['seedrow'], equation='nkrc,rn,k->nc'),
        helper.make_node('Einsum', ['input', 'colsel_f', 'kvec'], ['seedcol'], equation='nkrc,nc,k->rn'),
        helper.make_node('Cast', ['seedrow'], ['srU'], to=2),
        helper.make_node('Cast', ['seedcol'], ['scU'], to=2),
        helper.make_node('Reshape', ['srU', 'sh4row'], ['sr4']),
        helper.make_node('QLinearConv', ['sr4', 'qs', 'qz', 'ones_row', 'qs', 'qz', 'qs', 'qz'], ['tr3'], dilations=[1, 3], kernel_shape=[1, 21], pads=[0, 30, 0, 30]),
        helper.make_node('QLinearConv', ['sr4', 'qs', 'qz', 'ones_row', 'qs', 'qz', 'qs', 'qz'], ['tr4'], dilations=[1, 4], kernel_shape=[1, 21], pads=[0, 40, 0, 40]),
        helper.make_node('Where', ['p4', 'tr4', 'tr3'], ['trow4']),
        helper.make_node('Reshape', ['trow4', 'shRow'], ['tiled_row1']),
        helper.make_node('Reshape', ['scU', 'sh4col'], ['sc4']),
        helper.make_node('QLinearConv', ['sc4', 'qs', 'qz', 'ones_col', 'qs', 'qz', 'qs', 'qz'], ['tc3'], dilations=[3, 1], kernel_shape=[21, 1], pads=[30, 0, 30, 0]),
        helper.make_node('QLinearConv', ['sc4', 'qs', 'qz', 'ones_col', 'qs', 'qz', 'qs', 'qz'], ['tc4'], dilations=[4, 1], kernel_shape=[21, 1], pads=[40, 0, 40, 0]),
        helper.make_node('Where', ['p4', 'tc4', 'tc3'], ['tcol4']),
        helper.make_node('Reshape', ['tcol4', 'shCol'], ['tiled_col1']),
        helper.make_node('Where', ['colin_b', 'tiled_row1', 'qz'], ['rowval']),
        helper.make_node('Where', ['ra_b', 'tiled_col1', 'qz'], ['colval_nc']),
        helper.make_node('Cast', ['rowsel_b'], ['rowsel8'], to=2),
        helper.make_node('Cast', ['rowin_b'], ['rowin8'], to=2),
        helper.make_node('Cast', ['colsel_b'], ['colsel8'], to=2),
        helper.make_node('Cast', ['colin_b'], ['colin8'], to=2),
        helper.make_node('Concat', ['rowsel8', 'colval_nc', 'rowin8'], ['Amm'], axis=1),
        helper.make_node('Concat', ['rowval', 'colsel8', 'colin8'], ['Bmm'], axis=0),
        helper.make_node('QLinearMatMul', ['Amm', 'qs', 'qz', 'Bmm', 'qs', 'qz', 'qs', 'qz'], ['label']),
        helper.make_node('Equal', ['label', 'chans'], ['output']),
    ]
    value_infos = [
    ]
    return model('task358_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
