"""Task 362 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApvEoO6AACAPwAAgD8AAIA/AACAPwAAAAAAAIA/AACAPwAAgD8AAIA/')),
        tensor('base', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('basis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsaqG/STGTv2X4hL8Df22/PA1Rv3SbNL+uKRi/zG/3vkCMvr6wqIW+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('Q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo5juO9AAAAAAAAAAAAAAAALGqhPwAAgD8AAIA/AAAAAA==')),
        tensor('mix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAHrEzczMPQ==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'scale', 'base'], ['weighted_count'], equation='bkpq,k,xy->bx'),
        helper.make_node('Gemm', ['weighted_count', 'base', 'base'], ['shift'], alpha=1000.0, beta=-18919.0),
        helper.make_node('Einsum', ['input', 'scale', 'basis'], ['row_moment'], equation='bkpq,k,ap->b'),
        helper.make_node('Einsum', ['input', 'scale', 'basis'], ['col_moment'], equation='bkpq,k,aq->b'),
        helper.make_node('Sum', ['row_moment', 'shift'], ['row_target_f']),
        helper.make_node('Sub', ['col_moment', 'shift'], ['col_target_f']),
        helper.make_node('Concat', ['row_target_f', 'base'], ['row_base'], axis=1),
        helper.make_node('Concat', ['col_target_f', 'base'], ['col_base'], axis=1),
        helper.make_node('Einsum', ['input', 'row_base', 'row_base', 'col_base', 'col_base', 'basis', 'basis', 'basis', 'basis', 'Q', 'Q', 'Q', 'Q', 'mix', 'scale'], ['output'], equation='bopq,ba,bd,be,bh,ur,vr,wc,xc,aus,dvs,ews,hxs,s,o->borc'),
    ]
    value_infos = [
    ]
    return model('task362_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
