"""Task 124 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ch0_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('ch0_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAABQAAAAAAAAAKAAAAAAAAAA==')),
        tensor('half_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA/')),
        tensor('row02_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAA')),
        tensor('shift_kernel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr//////////wEAAAAAAAAA')),
        tensor('p3a_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('p3b_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAAAAAA==')),
        tensor('three_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('source_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDUsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoaAAAACAAAABoAAAAIAAAAGgAAABgAAAAFAAAAFwAAAAQAAAAWAAAAFgAAAAIAAAAUAAAAAAAAABIAAAAkAAAACAAAABoAAAAkAAAACAAAAA==')),
        tensor('col_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('row_flat_shape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('false8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('bg_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('pad_full', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
        tensor('channel_idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'ch0_starts', 'ch0_ends'], ['ch0_first5']),
        helper.make_node('Less', ['ch0_first5', 'half_f'], ['fg5']),
        helper.make_node('Gather', ['fg5', 'row02_idx'], ['fg02'], axis=2),
        helper.make_node('Cast', ['fg02'], ['fg02_u8'], to=2),
        helper.make_node('ArgMax', ['fg02_u8'], ['left_cols'], axis=3, keepdims=0),
        helper.make_node('MatMul', ['left_cols', 'shift_kernel'], ['shift']),
        helper.make_node('Gather', ['fg5', 'p3a_idx'], ['p3_rows_a'], axis=2),
        helper.make_node('Gather', ['fg5', 'p3b_idx'], ['p3_rows_b'], axis=2),
        helper.make_node('Equal', ['p3_rows_a', 'p3_rows_b'], ['p3_equal']),
        helper.make_node('Cast', ['p3_equal'], ['p3_equal_u8'], to=2),
        helper.make_node('ReduceMin', ['p3_equal_u8'], ['p3_all_equal'], axes=[0, 1, 2], keepdims=0),
        helper.make_node('Cast', ['p3_all_equal'], ['is_p3'], to=9),
        helper.make_node('Where', ['is_p3', 'three_i64', 'shift'], ['candidate']),
        helper.make_node('Gather', ['source_offsets', 'candidate'], ['source_offset'], axis=0),
        helper.make_node('Add', ['source_offset', 'col_idx'], ['fg_source_map']),
        helper.make_node('Split', ['fg02'], ['row0_4d', 'row2_4d'], axis=2, split=[1, 1]),
        helper.make_node('Reshape', ['row0_4d', 'row_flat_shape'], ['row0_flat']),
        helper.make_node('Reshape', ['p3_rows_a', 'row_flat_shape'], ['row1_flat']),
        helper.make_node('Reshape', ['row2_4d', 'row_flat_shape'], ['row2_flat']),
        helper.make_node('Concat', ['false8', 'row0_flat', 'false8', 'row1_flat', 'row2_flat'], ['fg_pad_flat'], axis=0),
        helper.make_node('Gather', ['fg_pad_flat', 'fg_source_map'], ['bottom_fg'], axis=0),
        helper.make_node('Concat', ['fg5', 'bottom_fg'], ['out_fg'], axis=2),
        helper.make_node('ReduceMax', ['input'], ['present_f'], axes=[2, 3], keepdims=1),
        helper.make_node('ArgMax', ['present_f'], ['color_idx_i64'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['color_idx_i64'], ['color_idx'], to=2),
        helper.make_node('Where', ['out_fg', 'color_idx', 'bg_idx'], ['color_crop']),
        helper.make_node('Pad', ['color_crop', 'pad_full'], ['color_full']),
        helper.make_node('Equal', ['color_full', 'channel_idx'], ['output']),
    ]
    value_infos = [
    ]
    return model('task124_live_exact', nodes, inits, output_dtype=9, opset=12, value_infos=value_infos)
