"""Task 203 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAPBA')),
        tensor('minus_one_i8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('zero10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
        tensor('colors', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('ReduceL1', ['input'], ['area_f'], axes=[0, 2, 3], keepdims=0),
        helper.make_node('QuantizeLinear', ['area_f', 'scale', 'minus_one_i8'], ['s_i8']),
        helper.make_node('Cast', ['s_i8'], ['s_i'], to=6),
        helper.make_node('ReduceMax', ['s_i'], ['outer_s'], axes=[0], keepdims=1),
        helper.make_node('Sub', ['outer_s', 's_i'], ['comp_s']),
        helper.make_node('ScatterElements', ['zero10', 's_i', 'colors'], ['by_s'], axis=0),
        helper.make_node('Gather', ['by_s', 'comp_s'], ['remap_u8'], axis=0),
        helper.make_node('Cast', ['remap_u8'], ['remap_i'], to=6),
        helper.make_node('Gather', ['input', 'remap_i'], ['output'], axis=1),
    ]
    value_infos = [
    ]
    return model('task203_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
