"""Task 339 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxLCA5KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00IAAOFEAAAWRAAAtENJkoBDAABIQ+miI0MndgpDAADwQsTD00I=')),
        tensor('b', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/AACAvwAAgL8AAIC/AACAvwAAgL8AAIC/AACAvwAAgL8AAIC/')),
    ]
    nodes = [
        helper.make_node('GlobalAveragePool', ['input'], ['avg']),
        helper.make_node('ConvTranspose', ['avg', 'w', 'b'], ['output'], group=10, kernel_shape=[1, 9], output_padding=[29, 21], strides=[30, 30]),
    ]
    value_infos = [
    ]
    return model('task339_live_exact', nodes, inits, output_dtype=1, opset=11, value_infos=value_infos)
