"""Task 377 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('cw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('ax0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('s0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('s1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('s30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAA==')),
        tensor('cendA', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoZAAAAAAAAAA==')),
        tensor('cendB', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoYAAAAAAAAAA==')),
        tensor('one_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('one1_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('zero8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('ar5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDUsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBA==')),
        tensor('depth30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoeAAAAAAAAAA==')),
        tensor('oh_vals', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
        tensor('two_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQA==')),
        tensor('ps1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAP//////////')),
        tensor('cwu', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('iv9', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDkpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEg=')),
        tensor('dvch', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDUsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBE')),
        tensor('vpad3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDYsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAAA=')),
        tensor('sh51', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAEAAAAAAAAA')),
        tensor('Sh5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDUsIDUpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAPAAAAAAAAAAAALwAPAAAAAAAAAAAALwAPAAAAAAAAAAAALwAPAAAAAAAAAAAALwAPA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'cw'], ['rowsum'], equation='nchw,c->h'),
        helper.make_node('Cast', ['rowsum'], ['rowsum_h'], to=10),
        helper.make_node('Pad', ['rowsum_h', 'ps1'], ['rs_shift'], mode='constant'),
        helper.make_node('Equal', ['rowsum_h', 'rs_shift'], ['rsame_full']),
        helper.make_node('Not', ['rsame_full'], ['rchg_full']),
        helper.make_node('Slice', ['rchg_full', 's1', 's30', 'ax0'], ['rchg']),
        helper.make_node('Cast', ['rchg'], ['rchg_h'], to=10),
        helper.make_node('ReduceSum', ['rchg_h', 'ax0'], ['Nv'], keepdims=0),
        helper.make_node('Div', ['Nv', 'two_h'], ['Rhalf']),
        helper.make_node('Floor', ['Rhalf'], ['Rf']),
        helper.make_node('CumSum', ['rchg_h', 'ax0'], ['cdepth']),
        helper.make_node('GreaterOrEqual', ['cdepth', 'Rf'], ['ge']),
        helper.make_node('Cast', ['ge'], ['ge_i8'], to=3),
        helper.make_node('ArgMax', ['ge_i8'], ['gstar'], axis=0, keepdims=1),
        helper.make_node('Add', ['gstar', 'one_i64'], ['rstar']),
        helper.make_node('OneHot', ['rstar', 'depth30', 'oh_vals'], ['rowmask'], axis=-1),
        helper.make_node('Einsum', ['input', 'cw', 'rowmask'], ['deeprow'], equation='nchw,c,nh->w'),
        helper.make_node('Cast', ['deeprow'], ['dr8'], to=2),
        helper.make_node('Slice', ['dr8', 's1', 'cendA', 'ax0'], ['dA']),
        helper.make_node('Slice', ['dr8', 's0', 'cendB', 'ax0'], ['dB']),
        helper.make_node('Equal', ['dA', 'dB'], ['dsame']),
        helper.make_node('Cast', ['dsame'], ['work0'], to=2),
        helper.make_node('Slice', ['dr8', 's0', 's1', 'ax0'], ['c0']),
        helper.make_node('ArgMin', ['work0'], ['p1'], axis=0, keepdims=1),
        helper.make_node('Gather', ['dA', 'p1'], ['c1'], axis=0),
        helper.make_node('ScatterElements', ['work0', 'p1', 'one1_u'], ['work1'], axis=0),
        helper.make_node('ArgMin', ['work1'], ['p2'], axis=0, keepdims=1),
        helper.make_node('Gather', ['dA', 'p2'], ['c2'], axis=0),
        helper.make_node('ScatterElements', ['work1', 'p2', 'one1_u'], ['work2'], axis=0),
        helper.make_node('ArgMin', ['work2'], ['p3'], axis=0, keepdims=1),
        helper.make_node('Gather', ['dA', 'p3'], ['c3'], axis=0),
        helper.make_node('ScatterElements', ['work2', 'p3', 'one1_u'], ['work3'], axis=0),
        helper.make_node('ArgMin', ['work3'], ['p4'], axis=0, keepdims=1),
        helper.make_node('Gather', ['dA', 'p4'], ['c4'], axis=0),
        helper.make_node('Concat', ['c0', 'c1', 'c2', 'c3', 'c4'], ['cvraw'], axis=0),
        helper.make_node('Cast', ['Rf'], ['R8'], to=2),
        helper.make_node('LessOrEqual', ['ar5', 'R8'], ['validk']),
        helper.make_node('Where', ['validk', 'cvraw', 'zero8'], ['colorvec']),
        helper.make_node('Mul', ['Rf', 'two_h'], ['twoN2_h']),
        helper.make_node('Sub', ['twoN2_h', 'iv9'], ['mirror']),
        helper.make_node('Min', ['iv9', 'mirror'], ['rd']),
        helper.make_node('GreaterOrEqual', ['rd', 'dvch'], ['V9b']),
        helper.make_node('Cast', ['V9b'], ['V9'], to=10),
        helper.make_node('Pad', ['V9', 'vpad3'], ['V'], mode='constant'),
        helper.make_node('Reshape', ['colorvec', 'sh51'], ['cv_col']),
        helper.make_node('Equal', ['cv_col', 'cwu'], ['Shot_b']),
        helper.make_node('Cast', ['Shot_b'], ['Shot'], to=10),
        helper.make_node('Einsum', ['Sh5', 'Shot', 'V', 'V'], ['output'], equation='de,ek,bdi,bdj->bkij'),
    ]
    value_infos = [
    ]
    return model('task377_live_exact', nodes, inits, output_dtype=10, opset=14, value_infos=value_infos)
