"""Task 029 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('iotar', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGosajCfMmo0hDWfNrk3ajj3OIQ5EjqfOiw7uTsjPGo8sTz3PD49hD3LPRI+WD6fPuY+LD9zP7k/AEA=')),
        tensor('iotac', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAGosajCfMmo0hDWfNrk3ajj3OIQ5EjqfOiw7uTsjPGo8sTz3PD49hD3LPRI+WD6fPuY+LD9zP7k/AEA=')),
        tensor('kf', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApqLA==')),
        tensor('km1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApzuw==')),
        tensor('cB', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAojvA==')),
        tensor('c3h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQg==')),
        tensor('axes_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('c4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAA')),
        tensor('c16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoQAAAA')),
        tensor('c7', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoHAAAA')),
        tensor('depth', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('onoff', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPw==')),
        tensor('v147_pads_36_14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAA')),
        tensor('v147_axes_36_15', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('v147_pads_49_16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input'], ['cntf'], equation='bchw->bc'),
        helper.make_node('Cast', ['cntf'], ['cnti'], to=6),
        helper.make_node('Mul', ['cnti', 'cnti'], ['cnt2']),
        helper.make_node('Einsum', ['input', 'input'], ['m2rf'], equation='bchw,bchv->bc'),
        helper.make_node('Cast', ['m2rf'], ['m2ri'], to=6),
        helper.make_node('Einsum', ['input', 'input'], ['m2cf'], equation='bchw,bcvw->bc'),
        helper.make_node('Cast', ['m2cf'], ['m2ci'], to=6),
        helper.make_node('Add', ['m2ri', 'm2ci'], ['msum']),
        helper.make_node('Mul', ['msum', 'c4'], ['msum4']),
        helper.make_node('Mul', ['cnti', 'c16'], ['c16n']),
        helper.make_node('Add', ['cnt2', 'c16n'], ['q1']),
        helper.make_node('Sub', ['msum4', 'q1'], ['q2']),
        helper.make_node('Add', ['q2', 'c16'], ['P']),
        helper.make_node('Mul', ['cnt2', 'P'], ['lhs']),
        helper.make_node('Sub', ['m2ri', 'm2ci'], ['d']),
        helper.make_node('Mul', ['d', 'd'], ['d2']),
        helper.make_node('Mul', ['d2', 'c4'], ['rhs']),
        helper.make_node('Equal', ['lhs', 'rhs'], ['eq1']),
        helper.make_node('Greater', ['cnti', 'c7'], ['ge8']),
        helper.make_node('And', ['eq1', 'ge8'], ['valid']),
        helper.make_node('Cast', ['valid'], ['vu8'], to=2),
        helper.make_node('ArgMax', ['vu8'], ['cstar'], axis=1, keepdims=1),
        helper.make_node('Unsqueeze', ['cstar', 'axes_e'], ['cstar3']),
        helper.make_node('OneHot', ['cstar3', 'depth', 'onoff'], ['e4'], axis=1),
        helper.make_node('Einsum', ['input', 'e4'], ['rcnt'], equation='bchw,bcxy->bhxy'),
        helper.make_node('ArgMax', ['rcnt'], ['rtop'], axis=1, keepdims=1),
        helper.make_node('ArgMax', ['rcnt'], ['rbot'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['rtop'], ['rtf'], to=10),
        helper.make_node('Mul', ['rtf', 'kf'], ['ra2']),
        helper.make_node('Add', ['ra2', 'km1'], ['ra3c']),
        helper.make_node('Add', ['iotar', 'ra3c'], ['rgin']),
        helper.make_node('Cast', ['rbot'], ['rbf'], to=10),
        helper.make_node('Mul', ['rbf', 'kf'], ['rbkf']),
        helper.make_node('Add', ['rbkf', 'cB'], ['rbthr']),
        helper.make_node('Less', ['rgin', 'rbthr'], ['rmask']),
        helper.make_node('Where', ['rmask', 'rgin', 'c3h'], ['rg']),
        helper.make_node('Pad', ['rg', 'v147_pads_36_14', '', 'v147_axes_36_15'], ['gypart']),
        helper.make_node('Einsum', ['input', 'e4'], ['ccnt'], equation='bchw,bcxy->bxwy'),
        helper.make_node('ArgMax', ['ccnt'], ['ctop'], axis=2, keepdims=1),
        helper.make_node('ArgMax', ['ccnt'], ['cbot'], axis=2, keepdims=1, select_last_index=1),
        helper.make_node('Cast', ['ctop'], ['ctf'], to=10),
        helper.make_node('Mul', ['ctf', 'kf'], ['ca2']),
        helper.make_node('Add', ['ca2', 'km1'], ['ca3c']),
        helper.make_node('Add', ['iotac', 'ca3c'], ['cgin']),
        helper.make_node('Cast', ['cbot'], ['cbf'], to=10),
        helper.make_node('Mul', ['cbf', 'kf'], ['cbkf']),
        helper.make_node('Add', ['cbkf', 'cB'], ['cbthr']),
        helper.make_node('Less', ['cgin', 'cbthr'], ['cmask']),
        helper.make_node('Where', ['cmask', 'cgin', 'c3h'], ['cg']),
        helper.make_node('Pad', ['cg', 'v147_pads_49_16', '', 'v147_axes_36_15'], ['gxpart']),
        helper.make_node('Add', ['gypart', 'gxpart'], ['grid']),
        helper.make_node('GridSample', ['input', 'grid'], ['output'], align_corners=1, mode='nearest', padding_mode='zeros'),
    ]
    value_infos = [
    ]
    return model('task029_live_exact', nodes, inits, output_dtype=1, opset=21, value_infos=value_infos)
