"""Task 028 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('q', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoLJm6/IjNHvwnuyD9nRzi/3fqtv8ZWy7+TUeK/BGAZwD9PxT9snx6/c/eKv0fKub8tkSu/IL+gv6xfv78iBgA/kO6tv8v6yr83Wvk+wWmlv0WByr+hsuU/yJM0wBEjRz8AVgM/qo26v7Suxb/UN9U/qZlZvxmyKz8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqijJ+7AA4/wG8Gzz66ztg9x7sYP1zekT5CJg6/ulAAwCBXqL8=')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'q', 'q', 'q', 'w'], ['output'], equation='nchk,ha,ra,wd,ad->ncrw'),
    ]
    value_infos = [
    ]
    return model('task028_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
