"""Task 242 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ch0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('pos', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqrquo/x3HcP+Q4zj8AAMA/HMexPzmOoz9VVZU/chyHPxzHcT9VVVU/juM4P8dxHD8AAAA/chzHPuQ4jj6rqio+OY5jPTmOY72rqiq+5DiOvnIcx74AAAC/x3Ecv47jOL9VVVW/HMdxv3Ich79VVZW/OY6jvxzHsb8=')),
        tensor('one_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('delta', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAAA3////9////8=')),
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('slice_steps', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA//////////8=')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAABsAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'ch0', 'pos'], ['row_f'], equation='nchw,c,h->n'),
        helper.make_node('Einsum', ['input', 'ch0', 'pos'], ['col_f'], equation='nchw,c,w->n'),
        helper.make_node('Cast', ['row_f'], ['row_i'], to=6),
        helper.make_node('Cast', ['col_f'], ['col_i'], to=6),
        helper.make_node('Concat', ['one_i', 'row_i', 'col_i'], ['starts'], axis=0),
        helper.make_node('Add', ['starts', 'delta'], ['ends']),
        helper.make_node('Slice', ['input', 'starts', 'ends', 'slice_axes', 'slice_steps'], ['patch9']),
        helper.make_node('Pad', ['patch9', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('patch9', 1, [1, 9, 3, 3]),
    ]
    return model('task242_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
