"""Task 034 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('x_st', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('x_en', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA==')),
        tensor('x_steps', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('zp_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('base_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/AQABAQEBAQEB')),
        tensor('k_ray_diag', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDgsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAgAAAAAAAAICAgAAAAAAAAICAgAAAAAAAAICAgAAAAAAAAICAgAAAAAAAAICAgAAAAAAAAICAgAAAAAAAAIC')),
        tensor('k_ray_anti', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDgsIDgpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAACAgAAAAAAAgICAAAAAAICAgAAAAACAgIAAAAAAgICAAAAAAICAgAAAAACAgIAAAAAAAICAAAAAAAA')),
        tensor('kq0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAgEBAQ==')),
        tensor('kq1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQIBAQ==')),
        tensor('kq2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQECAQ==')),
        tensor('kq3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQEBAg==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'x_st', 'x_en', '', 'x_steps'], ['x2']),
        helper.make_node('Cast', ['x2'], ['x2u'], to=2),
        helper.make_node('QLinearConv', ['x2u', 'scale', 'zp_u8', 'kq0', 'scale', 'one_u8', 'scale', 'zp_u8'], ['d0']),
        helper.make_node('QLinearConv', ['d0', 'scale', 'zp_u8', 'k_ray_diag', 'scale', 'zp_u8', 'scale', 'zp_u8'], ['r0'], pads=[2, 2, 8, 8]),
        helper.make_node('QLinearConv', ['x2u', 'scale', 'zp_u8', 'kq1', 'scale', 'one_u8', 'scale', 'zp_u8'], ['d1']),
        helper.make_node('QLinearConv', ['d1', 'scale', 'zp_u8', 'k_ray_anti', 'scale', 'zp_u8', 'scale', 'zp_u8'], ['r1'], pads=[2, 8, 8, 2]),
        helper.make_node('QLinearConv', ['x2u', 'scale', 'zp_u8', 'kq2', 'scale', 'one_u8', 'scale', 'zp_u8'], ['d2']),
        helper.make_node('QLinearConv', ['d2', 'scale', 'zp_u8', 'k_ray_anti', 'scale', 'zp_u8', 'scale', 'zp_u8'], ['r2'], pads=[8, 2, 2, 8]),
        helper.make_node('QLinearConv', ['x2u', 'scale', 'zp_u8', 'kq3', 'scale', 'one_u8', 'scale', 'zp_u8'], ['d3']),
        helper.make_node('QLinearConv', ['d3', 'scale', 'zp_u8', 'k_ray_diag', 'scale', 'zp_u8', 'scale', 'zp_u8'], ['r3'], pads=[8, 8, 2, 2]),
        helper.make_node('Max', ['r0', 'r1', 'r2', 'r3'], ['ray_u']),
        helper.make_node('GlobalMaxPool', ['input'], ['present']),
        helper.make_node('Cast', ['present'], ['present_u8'], to=2),
        helper.make_node('Transpose', ['present_u8'], ['present_t'], perm=[1, 0, 2, 3]),
        helper.make_node('Add', ['base_w', 'present_t'], ['w1x1']),
        helper.make_node('ConvInteger', ['ray_u', 'w1x1', 'one_u8', 'one_u8'], ['output'], pads=[0, 0, 21, 21]),
    ]
    value_infos = [
    ]
    return model('task034_live_exact', nodes, inits, output_dtype=6, opset=18, value_infos=value_infos)
