"""Task 118 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('qscale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqBgIA7')),
        tensor('qzp', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('scoreK2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAFAAAAAAAABQAAAAAFBQKFBQAAAAAFAAAAAAAABQAAAAAAAAAAAAA')),
        tensor('scoreK3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDcsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAUAAAAAAAAFAAAAAAAABQAAAAUFBQKFBQUAAAAFAAAAAAAABQAAAAAAAAUAAAA')),
        tensor('onehot8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAA')),
        tensor('sl_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('sl_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAAGQAAAAAAAAAbAAAAAAAAAA==')),
        tensor('pads_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAADAAAAAAAAAA==')),
        tensor('pad_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'sl_s', 'sl_e'], ['ch2']),
        helper.make_node('QuantizeLinear', ['ch2', 'qscale', 'qzp'], ['ch2_u8']),
        helper.make_node('QLinearConv', ['ch2_u8', 'qscale', 'qzp', 'scoreK2', 'qscale', 'qzp', 'qscale', 'qzp'], ['s2'], pads=[1, 2, 1, 0], strides=[1, 1]),
        helper.make_node('QLinearConv', ['ch2_u8', 'qscale', 'qzp', 'scoreK3', 'qscale', 'qzp', 'qscale', 'qzp'], ['s3'], pads=[1, 2, 1, 0], strides=[1, 1]),
        helper.make_node('ReduceMax', ['s2'], ['m2'], keepdims=0),
        helper.make_node('ReduceMax', ['s3'], ['m3'], keepdims=0),
        helper.make_node('GreaterOrEqual', ['m2', 'm3'], ['useArm2']),
        helper.make_node('Where', ['useArm2', 's2', 's3'], ['score']),
        helper.make_node('MaxPool', ['score'], ['pool'], kernel_shape=[11, 11], pads=[5, 5, 5, 5], strides=[1, 1]),
        helper.make_node('Equal', ['score', 'pool'], ['is_max']),
        helper.make_node('Where', ['is_max', 'score', 'qzp'], ['cand']),
        helper.make_node('Where', ['useArm2', 'scoreK2', 'scoreK3'], ['selK']),
        helper.make_node('QLinearConv', ['cand', 'qscale', 'qzp', 'selK', 'qscale', 'qzp', 'qscale', 'qzp'], ['expanded'], pads=[5, 4, 5, 6], strides=[1, 1]),
        helper.make_node('Less', ['ch2_u8', 'expanded'], ['mask_crop']),
        helper.make_node('Pad', ['mask_crop', 'pads_hw', '', 'pad_axes'], ['mask_b'], mode='constant'),
        helper.make_node('Where', ['mask_b', 'onehot8', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task118_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
