"""Task 248 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('period_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAKBA')),
        tensor('period_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr+')),
        tensor('row_offsets', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDksIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJCAcGBQQDAgE=')),
        tensor('updates', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDIsIDksIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8=')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['total_f'], keepdims=0),
        helper.make_node('QuantizeLinear', ['total_f', 'period_scale', 'period_zero'], ['period']),
        helper.make_node('Mod', ['row_offsets', 'period'], ['phase']),
        helper.make_node('Sub', ['period', 'phase'], ['reflected']),
        helper.make_node('Min', ['phase', 'reflected'], ['path_cols']),
        helper.make_node('Concat', ['path_cols', 'path_cols'], ['indices_i8'], axis=1),
        helper.make_node('Cast', ['indices_i8'], ['indices_i32'], to=6),
        helper.make_node('ScatterElements', ['input', 'indices_i32', 'updates'], ['output'], axis=3),
    ]
    value_infos = [
    ]
    return model('task248_live_exact', nodes, inits, output_dtype=1, opset=14, value_infos=value_infos)
