"""Task 241 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
    ]
    nodes = [
        helper.make_node('Transpose', ['input'], ['output'], perm=[0, 1, 3, 2]),
    ]
    value_infos = [
    ]
    return model('task241_live_exact', nodes, inits, output_dtype=1, opset=11, value_infos=value_infos)
