"""Task 329 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('idx_sq9_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDksKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgEAAABBBAACAQQAAyEEAABBCAABEQgAAgEI=')),
        tensor('center_counts5_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDUsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAQQQAAyEEAAERCAACiQg==')),
        tensor('color0_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('pad_out_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAABUAAAAAAAAA')),
        tensor('true_b', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('axis1_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('scatter_updates_b', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['cell_count_f'], keepdims=0),
        helper.make_node('LessOrEqual', ['cell_count_f', 'idx_sq9_f'], ['out9_b']),
        helper.make_node('Pad', ['out9_b', 'pad_out_i64', 'true_b'], ['out_by_index_b'], mode='constant'),
        helper.make_node('Unsqueeze', ['out_by_index_b', 'axis1_i64'], ['row_out_b']),
        helper.make_node('Equal', ['cell_count_f', 'center_counts5_f'], ['center5_b']),
        helper.make_node('Cast', ['center5_b'], ['center5_u8'], to=2),
        helper.make_node('ArgMax', ['center5_u8'], ['center_idx_i64'], axis=0, keepdims=1),
        helper.make_node('ScatterElements', ['out_by_index_b', 'center_idx_i64', 'scatter_updates_b'], ['col_keep_b'], axis=0),
        helper.make_node('Or', ['row_out_b', 'col_keep_b'], ['keep_input_b']),
        helper.make_node('Where', ['keep_input_b', 'input', 'color0_f'], ['output']),
    ]
    value_infos = [
    ]
    return model('task329_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
