"""Task 143 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('x', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAABDAAADgvwAAoL8AAEC/AACAvgAAgD4AAEA/AACgPwAA4D8AABBAAAAwQAAAUEAAAHBAAACIQAAAmEAAAKhAAAC4QAAAyEAAANhAAADoQAAA+EAAAARBAAAMQQAAFEEAABxBAAAkQQAALEEAADRBAAA8QQAAREE=')),
        tensor('negx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAABBAAADgPwAAoD8AAEA/AACAPgAAgL4AAEC/AACgvwAA4L8AABDAAAAwwAAAUMAAAHDAAACIwAAAmMAAAKjAAAC4wAAAyMAAANjAAADowAAA+MAAAATBAAAMwQAAFMEAABzBAAAkwQAALMEAADTBAAA8wQAARME=')),
        tensor('update', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAvwAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgL8AAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAvwAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC/AACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AACAvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAIC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAAAAAAAAAAgL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAACAvw==')),
        tensor('slot', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAAAAAAAAAA')),
        tensor('axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('true', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'input', 'x', 'x'], ['T1'], equation='bkhw,bkij,i,i->bk'),
        helper.make_node('Einsum', ['input', 'input', 'negx', 'x'], ['T2'], equation='bkhw,bkij,h,i->bk'),
        helper.make_node('Einsum', ['input', 'input', 'x', 'x'], ['T3'], equation='bkhw,bkij,i,j->bk'),
        helper.make_node('Einsum', ['input', 'input', 'negx', 'x'], ['T4'], equation='bkhw,bkij,h,j->bk'),
        helper.make_node('Einsum', ['input', 'input', 'input', 'x', 'x', 'x'], ['T5'], equation='bkhw,bkij,bkpq,p,p,p->bk'),
        helper.make_node('Einsum', ['input', 'input', 'input', 'negx', 'x', 'x'], ['T6'], equation='bkhw,bkij,bkpq,i,p,p->bk'),
        helper.make_node('Einsum', ['input', 'input', 'input', 'x', 'x', 'x'], ['T7'], equation='bkhw,bkij,bkpq,h,i,p->bk'),
        helper.make_node('Sum', ['T1', 'T2', 'T3', 'T3', 'T4', 'T4', 'T5', 'T5', 'T5', 'T5', 'T5', 'T5', 'T5', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T6', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7', 'T7'], ['H']),
        helper.make_node('MaxPool', ['input'], ['ref10'], kernel_shape=[3, 3], strides=[30, 30]),
        helper.make_node('Einsum', ['ref10', 'slot'], ['refi_f'], equation='bkuv,k->b'),
        helper.make_node('Cast', ['refi_f'], ['refi'], to=6),
        helper.make_node('Gather', ['H', 'refi'], ['refH'], axis=1),
        helper.make_node('Equal', ['H', 'refH'], ['match']),
        helper.make_node('Equal', ['refi_f', 'slot'], ['ref_b']),
        helper.make_node('Xor', ['match', 'ref_b'], ['target_b']),
        helper.make_node('Pad', ['target_b', 'pads', 'true', 'axes'], ['U_b'], mode='constant'),
        helper.make_node('Cast', ['U_b'], ['U'], to=1),
        helper.make_node('Einsum', ['input', 'U', 'update'], ['output'], equation='bkhw,tk,tko->bohw'),
    ]
    value_infos = [
    ]
    return model('task143_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
