"""Task 121 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('axes123', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('three8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('zero8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('zero32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('one32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('chan8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgD8AAAAA')),
        tensor('coord', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAABAAABAQAAAgEAAAKBAAADAQAAA4EAAAABBAAAQQQAAIEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('zero_sel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAAA')),
        tensor('pad18_pads_28_11', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGwAAAAAAAAAbAAAAAAAAAA==')),
        tensor('pad18_axes_28_12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'chan8', 'coord'], ['row_f'], equation='bcrs,c,r->b'),
        helper.make_node('Einsum', ['input', 'chan8', 'coord'], ['col_f'], equation='bcrs,c,s->b'),
        helper.make_node('Cast', ['row_f'], ['row8'], to=3),
        helper.make_node('Cast', ['col_f'], ['col8'], to=3),
        helper.make_node('Concat', ['row8', 'col8'], ['s2_8'], axis=0),
        helper.make_node('Add', ['s2_8', 'three8'], ['e2_8']),
        helper.make_node('Concat', ['zero8', 's2_8'], ['bgs3_8'], axis=0),
        helper.make_node('Concat', ['one8', 'e2_8'], ['bge3_8'], axis=0),
        helper.make_node('Cast', ['bgs3_8'], ['bg_starts3'], to=6),
        helper.make_node('Cast', ['bge3_8'], ['bg_ends3'], to=6),
        helper.make_node('Slice', ['input', 'bg_starts3', 'bg_ends3', 'axes123'], ['bg_patch']),
        helper.make_node('Cast', ['bg_patch'], ['patch_bg'], to=9),
        helper.make_node('Gather', ['patch_bg', 'zero32'], ['top_bg'], axis=2),
        helper.make_node('Gather', ['top_bg', 'zero32'], ['top_b0'], axis=3),
        helper.make_node('Gather', ['top_bg', 'one32'], ['top_b1'], axis=3),
        helper.make_node('And', ['top_b0', 'top_b1'], ['top_b0b1']),
        helper.make_node('Cast', ['top_b0'], ['b0_8'], to=3),
        helper.make_node('Cast', ['top_b0b1'], ['b01_8'], to=3),
        helper.make_node('Add', ['b0_8', 'b01_8'], ['off4d_8']),
        helper.make_node('Squeeze', ['off4d_8'], ['off_8']),
        helper.make_node('Add', ['col8', 'off_8'], ['color_col8']),
        helper.make_node('Concat', ['row8', 'color_col8'], ['cs2_8'], axis=0),
        helper.make_node('Add', ['cs2_8', 'one8'], ['ce2_8']),
        helper.make_node('Cast', ['cs2_8'], ['color_starts2'], to=6),
        helper.make_node('Cast', ['ce2_8'], ['color_ends2'], to=6),
        helper.make_node('Slice', ['input', 'color_starts2', 'color_ends2', 'axes23'], ['color_pixel']),
        helper.make_node('Cast', ['color_pixel'], ['color_selector'], to=2),
        helper.make_node('Where', ['patch_bg', 'zero_sel', 'color_selector'], ['small']),
        helper.make_node('Pad', ['small', 'pad18_pads_28_11', '', 'pad18_axes_28_12'], ['output'], mode='constant'),
    ]
    value_infos = [
        helper.make_tensor_value_info('row_f', 1, [1]),
        helper.make_tensor_value_info('col_f', 1, [1]),
        helper.make_tensor_value_info('row8', 3, [1]),
        helper.make_tensor_value_info('col8', 3, [1]),
        helper.make_tensor_value_info('s2_8', 3, [2]),
        helper.make_tensor_value_info('e2_8', 3, [2]),
        helper.make_tensor_value_info('bgs3_8', 3, [3]),
        helper.make_tensor_value_info('bge3_8', 3, [3]),
        helper.make_tensor_value_info('bg_starts3', 6, [3]),
        helper.make_tensor_value_info('bg_ends3', 6, [3]),
        helper.make_tensor_value_info('bg_patch', 1, [1, 1, 3, 3]),
        helper.make_tensor_value_info('patch_bg', 9, [1, 1, 3, 3]),
        helper.make_tensor_value_info('top_bg', 9, [1, 1, 1, 3]),
        helper.make_tensor_value_info('top_b0', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b1', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('top_b0b1', 9, [1, 1, 1, 1]),
        helper.make_tensor_value_info('b0_8', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('b01_8', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('off4d_8', 3, [1, 1, 1, 1]),
        helper.make_tensor_value_info('off_8', 3, []),
        helper.make_tensor_value_info('color_col8', 3, [1]),
        helper.make_tensor_value_info('cs2_8', 3, [2]),
        helper.make_tensor_value_info('ce2_8', 3, [2]),
        helper.make_tensor_value_info('color_starts2', 6, [2]),
        helper.make_tensor_value_info('color_ends2', 6, [2]),
        helper.make_tensor_value_info('color_pixel', 1, [1, 10, 1, 1]),
        helper.make_tensor_value_info('color_selector', 2, [1, 10, 1, 1]),
        helper.make_tensor_value_info('small', 2, [1, 10, 3, 3]),
    ]
    return model('task121_live_exact', nodes, inits, output_dtype=2, opset=18, value_infos=value_infos)
