"""Task 024 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('basis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoim/4/LrDyPoZ17UA5v46/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAy+1nvoHnkr97UI09r+WKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKCvFUB1wI0+1ZOowM7Gt70AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDCk+/3ox7wBLgOsD8tFvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('mix', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAouL0E+5F0UP9YnkMCT8/c/tSoNwJKKGECWrkG/AgoyvlmXfz+u17E/pG1uQEIK778WZ4VA2zagQFzZIL/6CIC/')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'input', 'input', 'basis', 'basis', 'basis', 'basis', 'mix', 'mix', 'mix'], ['output'], equation='nchw,ndhp,neij,fc,ld,ge,tk,ft,lt,gt->nkhj'),
    ]
    value_infos = [
    ]
    return model('task024_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
