"""Task 245 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes_c_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('start_c2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('end_c2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAkAAAAAAAAACQAAAAAAAAA=')),
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('axes_reduce_row', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAMAAAAAAAAA')),
        tensor('axes_reduce_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAA')),
        tensor('chan3_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('coord30_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAEC/AAAAvwAAgL4AAAAAAACAPgAAAD8AAEA/AACAPwAAoD8AAMA/AADgPwAAAEAAABBAAAAgQAAAMEAAAEBAAABQQAAAYEAAAHBAAACAQAAAiEAAAJBAAACYQAAAoEAAAKhAAACwQAAAuEAAAMBAAADIQAAA0EA=')),
        tensor('const1_i8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('const3_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('const13_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoNAAAA')),
        tensor('frame_base', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEzLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAABAAAAAAABAAAA')),
        tensor('frame_axis', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAA')),
        tensor('coord_tail_row_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAABAQQAAwEE=')),
        tensor('coord_tail_col_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAABAQQAAwEE=')),
        tensor('pads_tail', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoHAAAAAAAAAAAAAAAAAAAA')),
        tensor('axis2_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('axis3_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('w_out', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAzLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB//8AAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'start_c2', 'end_c2', 'axes_c_hw'], ['c2']),
        helper.make_node('Einsum', ['input', 'coord30_f'], ['row_sum_s'], equation='nchw,h->n'),
        helper.make_node('Einsum', ['input', 'coord30_f'], ['col_sum_s'], equation='nchw,w->n'),
        helper.make_node('Less', ['coord_tail_row_f', 'row_sum_s'], ['row_tail_b']),
        helper.make_node('Less', ['coord_tail_col_f', 'col_sum_s'], ['col_tail_b']),
        helper.make_node('Cast', ['row_tail_b'], ['row_tail_u'], to=3),
        helper.make_node('Cast', ['col_tail_b'], ['col_tail_u'], to=3),
        helper.make_node('Pad', ['row_tail_u', 'pads_tail', 'const1_i8', 'axis2_i64'], ['rowu'], mode='constant'),
        helper.make_node('Pad', ['col_tail_u', 'pads_tail', 'const1_i8', 'axis3_i64'], ['colu'], mode='constant'),
        helper.make_node('Cast', ['c2'], ['old2u'], to=3),
        helper.make_node('ReduceMax', ['old2u', 'axes_reduce_row'], ['c2_row_any'], keepdims=0),
        helper.make_node('ReduceMax', ['old2u', 'axes_reduce_col'], ['c2_col_any'], keepdims=0),
        helper.make_node('ArgMax', ['c2_row_any'], ['c2_y0'], axis=1, keepdims=0),
        helper.make_node('ArgMax', ['c2_col_any'], ['c2_x0'], axis=1, keepdims=0),
        helper.make_node('Cast', ['c2_y0'], ['c2_y0_i8'], to=3),
        helper.make_node('Cast', ['c2_x0'], ['c2_x0_i8'], to=3),
        helper.make_node('Einsum', ['input', 'chan3_f', 'coord30_f'], ['c3_yf'], equation='nchw,c,h->n'),
        helper.make_node('Einsum', ['input', 'chan3_f', 'coord30_f'], ['c3_xf'], equation='nchw,c,w->n'),
        helper.make_node('Cast', ['c3_yf'], ['c3_y0'], to=6),
        helper.make_node('Cast', ['c3_xf'], ['c3_x0'], to=6),
        helper.make_node('Cast', ['c3_y0'], ['c3_y0_i8'], to=3),
        helper.make_node('Cast', ['c3_x0'], ['c3_x0_i8'], to=3),
        helper.make_node('Sub', ['c2_y0_i8', 'c3_y0_i8'], ['shift_bottom']),
        helper.make_node('Sub', ['const1_i8', 'shift_bottom'], ['shift_top']),
        helper.make_node('Sub', ['c2_x0_i8', 'c3_x0_i8'], ['shift_right']),
        helper.make_node('Sub', ['const1_i8', 'shift_right'], ['shift_left']),
        helper.make_node('Concat', ['shift_top', 'shift_left', 'shift_bottom', 'shift_right'], ['pads_shift_i32'], axis=0),
        helper.make_node('Cast', ['pads_shift_i32'], ['pads_shift'], to=7),
        helper.make_node('Pad', ['old2u', 'pads_shift', '', 'axes_hw'], ['n2u'], mode='constant'),
        helper.make_node('Sub', ['const3_i32', 'c3_y0'], ['fy0']),
        helper.make_node('Sub', ['const13_i32', 'c3_y0'], ['fy1']),
        helper.make_node('Sub', ['const3_i32', 'c3_x0'], ['fx0']),
        helper.make_node('Sub', ['const13_i32', 'c3_x0'], ['fx1']),
        helper.make_node('Slice', ['frame_base', 'fy0', 'fy1', 'frame_axis'], ['c3_rows4']),
        helper.make_node('Slice', ['frame_base', 'fx0', 'fx1', 'frame_axis'], ['c3_col_pre']),
        helper.make_node('Transpose', ['c3_col_pre'], ['c3_cols4'], perm=[0, 1, 3, 2]),
        helper.make_node('Mul', ['c3_rows4', 'c3_cols4'], ['c3u']),
        helper.make_node('Mul', ['rowu', 'colu'], ['grid_all']),
        helper.make_node('Concat', ['grid_all', 'n2u', 'c3u'], ['feat3'], axis=1),
        helper.make_node('ConvInteger', ['feat3', 'w_out'], ['output'], pads=[0, 0, 20, 20]),
    ]
    value_infos = [
        helper.make_tensor_value_info('n2u', 3, [1, 1, 10, 10]),
        helper.make_tensor_value_info('c3_rows4', 3, [1, 1, 10, 1]),
        helper.make_tensor_value_info('c3_col_pre', 3, [1, 1, 10, 1]),
    ]
    return model('task245_live_exact', nodes, inits, output_dtype=6, opset=18, value_infos=value_infos)
