"""Task 384 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('crop_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAAAQAAAAEAAAA=')),
        tensor('crop_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAACAAAAAgAAAA=')),
        tensor('crop_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('fg_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('fg_size', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAAAABQAAAA==')),
        tensor('W', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAvAC8ALwAvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8ADwAPAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'crop_starts', 'crop_ends', 'crop_axes'], ['crop_f32']),
        helper.make_node('Cast', ['crop_f32'], ['crop_i8'], to=3),
        helper.make_node('ReduceMax', ['crop_i8'], ['row_has'], axes=[0, 1, 3], keepdims=0),
        helper.make_node('ReduceMax', ['crop_i8'], ['col_has'], axes=[0, 1, 2], keepdims=0),
        helper.make_node('ArgMax', ['row_has'], ['top64'], axis=0, keepdims=1),
        helper.make_node('ArgMax', ['col_has'], ['left64'], axis=0, keepdims=1),
        helper.make_node('Cast', ['top64'], ['top'], to=6),
        helper.make_node('Cast', ['left64'], ['left'], to=6),
        helper.make_node('Concat', ['top', 'left'], ['fg_starts'], axis=0),
        helper.make_node('Add', ['fg_starts', 'fg_size'], ['fg_ends']),
        helper.make_node('Slice', ['crop_i8', 'fg_starts', 'fg_ends', 'fg_axes'], ['fg_small']),
        helper.make_node('ReduceMax', ['fg_small'], ['row_span'], axes=[0, 1, 3], keepdims=1),
        helper.make_node('ReduceMax', ['fg_small'], ['col_span'], axes=[0, 1, 2], keepdims=1),
        helper.make_node('Mul', ['row_span', 'col_span'], ['extent']),
        helper.make_node('Add', ['fg_small', 'fg_small'], ['fg2']),
        helper.make_node('Sub', ['fg2', 'extent'], ['signed_i8']),
        helper.make_node('Cast', ['signed_i8'], ['signed_f16'], to=10),
        helper.make_node('ConvTranspose', ['signed_f16', 'W'], ['output'], pads=[0, 0, -22, -20], strides=[2, 2]),
    ]
    value_infos = [
        helper.make_tensor_value_info('crop_f32', 1, [1, 1, 7, 7]),
        helper.make_tensor_value_info('crop_i8', 3, [1, 1, 7, 7]),
        helper.make_tensor_value_info('row_has', 3, [7]),
        helper.make_tensor_value_info('col_has', 3, [7]),
        helper.make_tensor_value_info('top64', 7, [1]),
        helper.make_tensor_value_info('left64', 7, [1]),
        helper.make_tensor_value_info('top', 6, [1]),
        helper.make_tensor_value_info('left', 6, [1]),
        helper.make_tensor_value_info('fg_starts', 6, [2]),
        helper.make_tensor_value_info('fg_ends', 6, [2]),
        helper.make_tensor_value_info('fg_small', 3, [1, 1, 4, 5]),
        helper.make_tensor_value_info('row_span', 3, [1, 1, 4, 1]),
        helper.make_tensor_value_info('col_span', 3, [1, 1, 1, 5]),
        helper.make_tensor_value_info('extent', 3, [1, 1, 4, 5]),
        helper.make_tensor_value_info('fg2', 3, [1, 1, 4, 5]),
        helper.make_tensor_value_info('signed_i8', 3, [1, 1, 4, 5]),
        helper.make_tensor_value_info('signed_f16', 10, [1, 1, 4, 5]),
    ]
    return model('task384_live_exact', nodes, inits, output_dtype=10, opset=17, value_infos=value_infos)
