"""Task 165 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('bg_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA==')),
        tensor('bg_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAFAAAAAAAAAASAAAAAAAAAA==')),
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('tmpl', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDQsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAABAAAAAAABAQEAAAABAQABAQABAAAAAAAB')),
        tensor('qsc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('qz', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('rowramp_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJCgsMDQ4PEBESEw==')),
        tensor('rowramp30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJCgsMDQ4PEBESEwAAAAAAAAAAAAA=')),
        tensor('arange30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAAB0AAAA=')),
        tensor('five', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAA')),
        tensor('Kshape', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDcpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQgBAAEAAPABAAEAAQg==')),
        tensor('half', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
        tensor('c99_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAowVg==')),
        tensor('c99_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApj')),
        tensor('maxrow_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAA')),
        tensor('rs5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDUsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAA')),
        tensor('zero_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDksIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('chan_col', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDksIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAA=')),
        tensor('zero_c1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'bg_starts', 'bg_ends'], ['bg']),
        helper.make_node('Equal', ['bg', 'zero_f'], ['colored_b']),
        helper.make_node('Cast', ['colored_b'], ['colored_u8'], to=2),
        helper.make_node('QLinearConv', ['colored_u8', 'qsc', 'qz', 'tmpl', 'qsc', 'qz', 'qsc', 'qz'], ['kcount']),
        helper.make_node('ReduceMax', ['kcount'], ['rowscore'], axes=[3], keepdims=0),
        helper.make_node('ArgMax', ['rowscore'], ['r0'], axis=2, keepdims=0),
        helper.make_node('ReduceMax', ['kcount'], ['colscore'], axes=[2], keepdims=0),
        helper.make_node('ArgMax', ['colscore'], ['c0'], axis=2, keepdims=0),
        helper.make_node('Cast', ['c0'], ['c0_i32'], to=6),
        helper.make_node('Add', ['c0_i32', 'five'], ['colk']),
        helper.make_node('Equal', ['arange30', 'colk'], ['col_oh_b']),
        helper.make_node('Cast', ['col_oh_b'], ['col_oh_f'], to=10),
        helper.make_node('Conv', ['col_oh_f', 'Kshape'], ['shape_placed'], pads=[0, 3, 0, 3]),
        helper.make_node('Greater', ['shape_placed', 'half'], ['kite_col_mask']),
        helper.make_node('Cast', ['r0'], ['rowk_f'], to=10),
        helper.make_node('Add', ['shape_placed', 'rowk_f'], ['botvals']),
        helper.make_node('Where', ['kite_col_mask', 'botvals', 'c99_f'], ['botKite_f']),
        helper.make_node('Cast', ['botKite_f'], ['botKite_u8'], to=2),
        helper.make_node('Where', ['colored_b', 'rowramp_col', 'qz'], ['rowidx']),
        helper.make_node('ReduceMax', ['rowidx'], ['maxrow16'], axes=[2], keepdims=1),
        helper.make_node('Pad', ['maxrow16', 'maxrow_pads', 'qz'], ['maxrow30']),
        helper.make_node('Greater', ['maxrow30', 'botKite_u8'], ['active30']),
        helper.make_node('Where', ['active30', 'botKite_u8', 'c99_u8'], ['botKite_fin']),
        helper.make_node('Greater', ['rowramp30', 'botKite_fin'], ['fill30']),
        helper.make_node('Where', ['active30', 'maxrow30', 'qz'], ['seed_score']),
        helper.make_node('ArgMax', ['seed_score'], ['scol'], axis=3, keepdims=0),
        helper.make_node('ReduceMax', ['seed_score'], ['srow_u8'], axes=[3], keepdims=0),
        helper.make_node('Cast', ['srow_u8'], ['srow_i64'], to=7),
        helper.make_node('Reshape', ['srow_i64', 'rs5'], ['srow5']),
        helper.make_node('Reshape', ['scol', 'rs5'], ['scol5']),
        helper.make_node('Add', ['zero_col', 'srow5'], ['row_col']),
        helper.make_node('Add', ['zero_col', 'scol5'], ['col_col']),
        helper.make_node('Concat', ['zero_col', 'chan_col', 'row_col', 'col_col'], ['seed_idx'], axis=4),
        helper.make_node('GatherND', ['input', 'seed_idx'], ['sparse9']),
        helper.make_node('Concat', ['zero_c1', 'sparse9'], ['sparse10'], axis=1),
        helper.make_node('Where', ['fill30', 'sparse10', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task165_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
