"""Task 228 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('coord_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('big_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoI')),
        tensor('zero_u8_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('two_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAQA==')),
        tensor('scatter_selector', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCA0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAACwAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABwAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAUAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAHAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAMAAAAAAAAACAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAsAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAYAAAAAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('scatter_updates', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAAAAAAAAAAAAgD8AAIA/AAAAAAAAAAAAAIA/AACAPwAAAAAAAAAAAACAPwAAgD8AAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'coord_weights'], ['row_sum'], equation='bchw,h->bc'),
        helper.make_node('Einsum', ['input', 'coord_weights'], ['col_sum'], equation='bchw,w->bc'),
        helper.make_node('Cast', ['row_sum'], ['row_u8'], to=2),
        helper.make_node('Cast', ['col_sum'], ['col_u8'], to=2),
        helper.make_node('Greater', ['row_u8', 'zero_u8_1'], ['row_pos']),
        helper.make_node('Less', ['row_u8', 'big_u8'], ['row_lt_big']),
        helper.make_node('Where', ['row_pos', 'row_u8', 'big_u8'], ['row_min_vals']),
        helper.make_node('Where', ['row_lt_big', 'row_u8', 'zero_u8_1'], ['row_max_vals']),
        helper.make_node('ReduceMin', ['row_min_vals'], ['row_min_u8'], axes=[1], keepdims=0),
        helper.make_node('ReduceMax', ['row_max_vals'], ['row_max_u8'], axes=[1], keepdims=0),
        helper.make_node('Equal', ['row_u8', 'row_min_u8'], ['row_eq_min']),
        helper.make_node('Equal', ['row_u8', 'row_max_u8'], ['row_eq_max']),
        helper.make_node('Where', ['row_eq_min', 'col_u8', 'big_u8'], ['top_col_min_vals']),
        helper.make_node('Where', ['row_eq_min', 'col_u8', 'zero_u8_1'], ['top_col_max_vals']),
        helper.make_node('Where', ['row_eq_max', 'col_u8', 'big_u8'], ['bottom_col_min_vals']),
        helper.make_node('Where', ['row_eq_max', 'col_u8', 'zero_u8_1'], ['bottom_col_max_vals']),
        helper.make_node('ReduceMin', ['top_col_min_vals'], ['col_min_u8'], axes=[1], keepdims=0),
        helper.make_node('ReduceMax', ['top_col_max_vals'], ['col_max_u8'], axes=[1], keepdims=0),
        helper.make_node('ArgMax', ['bottom_col_max_vals'], ['br_color_i'], axis=1, keepdims=0),
        helper.make_node('ArgMin', ['bottom_col_min_vals'], ['bl_color_i'], axis=1, keepdims=0),
        helper.make_node('ArgMax', ['top_col_max_vals'], ['tr_color_i'], axis=1, keepdims=0),
        helper.make_node('ArgMin', ['top_col_min_vals'], ['tl_color_i'], axis=1, keepdims=0),
        helper.make_node('Cast', ['br_color_i'], ['br_color_u8'], to=2),
        helper.make_node('Cast', ['bl_color_i'], ['bl_color_u8'], to=2),
        helper.make_node('Cast', ['tr_color_i'], ['tr_color_u8'], to=2),
        helper.make_node('Cast', ['tl_color_i'], ['tl_color_u8'], to=2),
        helper.make_node('Cast', ['row_min_u8'], ['row_min_f16'], to=10),
        helper.make_node('Cast', ['row_max_u8'], ['row_max_f16'], to=10),
        helper.make_node('Cast', ['col_min_u8'], ['col_min_f16'], to=10),
        helper.make_node('Cast', ['col_max_u8'], ['col_max_f16'], to=10),
        helper.make_node('Sub', ['row_min_f16', 'two_f16'], ['row_top_outer_f16']),
        helper.make_node('Cast', ['row_top_outer_f16'], ['row_top_outer_u8'], to=2),
        helper.make_node('Add', ['row_max_f16', 'two_f16'], ['row_bottom_outer_f16']),
        helper.make_node('Cast', ['row_bottom_outer_f16'], ['row_bottom_outer_u8'], to=2),
        helper.make_node('Sub', ['col_min_f16', 'two_f16'], ['col_left_outer_f16']),
        helper.make_node('Cast', ['col_left_outer_f16'], ['col_left_outer_u8'], to=2),
        helper.make_node('Add', ['col_max_f16', 'two_f16'], ['col_right_outer_f16']),
        helper.make_node('Cast', ['col_right_outer_f16'], ['col_right_outer_u8'], to=2),
        helper.make_node('Concat', ['zero_u8_1', 'br_color_u8', 'bl_color_u8', 'tr_color_u8', 'tl_color_u8', 'row_top_outer_u8', 'row_min_u8', 'row_max_u8', 'row_bottom_outer_u8', 'col_left_outer_u8', 'col_min_u8', 'col_max_u8', 'col_right_outer_u8'], ['vars_u8'], axis=0),
        helper.make_node('Gather', ['vars_u8', 'scatter_selector'], ['scatter_indices_u8'], axis=0),
        helper.make_node('Cast', ['scatter_indices_u8'], ['scatter_indices'], to=7),
        helper.make_node('ScatterND', ['input', 'scatter_indices', 'scatter_updates'], ['output']),
    ]
    value_infos = [
    ]
    return model('task228_live_exact', nodes, inits, output_dtype=1, opset=12, value_infos=value_infos)
