"""Task 183 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('mw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAAAAABBB')),
        tensor('sel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('cids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDYpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAU=')),
        tensor('four', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoE')),
        tensor('two', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('sst', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAgAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA==')),
        tensor('sen', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAkAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAA==')),
        tensor('paxes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'sel'], ['Kf'], equation='ncij,j->'),
        helper.make_node('Cast', ['Kf'], ['K'], to=2),
        helper.make_node('Einsum', ['input', 'mw'], ['tot'], equation='ncij,c->'),
        helper.make_node('Einsum', ['input', 'mw', 'sel'], ['A'], equation='ncij,c,j->'),
        helper.make_node('Einsum', ['input', 'mw', 'sel'], ['B'], equation='ncij,c,i->'),
        helper.make_node('Einsum', ['input', 'mw', 'sel', 'sel'], ['TLv'], equation='ncij,c,i,j->'),
        helper.make_node('Cast', ['tot'], ['totu'], to=2),
        helper.make_node('Cast', ['A'], ['au'], to=2),
        helper.make_node('Cast', ['B'], ['bu'], to=2),
        helper.make_node('Cast', ['TLv'], ['tlu'], to=2),
        helper.make_node('Sub', ['au', 'tlu'], ['BLv']),
        helper.make_node('Sub', ['bu', 'tlu'], ['TRv']),
        helper.make_node('Sub', ['totu', 'au'], ['trbr']),
        helper.make_node('Sub', ['trbr', 'TRv'], ['BRv']),
        helper.make_node('Sub', ['K', 'four'], ['M']),
        helper.make_node('Div', ['M', 'two'], ['half']),
        helper.make_node('Less', ['r', 'half'], ['left']),
        helper.make_node('Transpose', ['left'], ['top'], perm=[1, 0]),
        helper.make_node('Where', ['left', 'tlu', 'TRv'], ['tc']),
        helper.make_node('Where', ['left', 'BLv', 'BRv'], ['bc']),
        helper.make_node('Where', ['top', 'tc', 'bc'], ['qc']),
        helper.make_node('Less', ['r', 'M'], ['cvalid']),
        helper.make_node('Transpose', ['cvalid'], ['rvalid'], perm=[1, 0]),
        helper.make_node('Where', ['cvalid', 'zero', 'totu'], ['cpen']),
        helper.make_node('Where', ['rvalid', 'zero', 'totu'], ['rpen']),
        helper.make_node('Max', ['rpen', 'cpen'], ['bgmap']),
        helper.make_node('Slice', ['input', 'sst', 'sen'], ['cr8']),
        helper.make_node('Cast', ['cr8'], ['m8'], to=9),
        helper.make_node('Where', ['m8', 'qc', 'bgmap'], ['lab']),
        helper.make_node('Equal', ['lab', 'cids'], ['sout']),
        helper.make_node('Pad', ['sout', 'pads', '', 'paxes'], ['output']),
    ]
    value_infos = [
    ]
    return model('task183_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
