"""Task 064 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ax23', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('zerof', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('twof', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABA')),
        tensor('uone', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('bfalse', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('pads_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input', 'ax23'], ['counts'], keepdims=1),
        helper.make_node('ArgMax', ['counts'], ['bg_idx'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('ScatterElements', ['counts', 'bg_idx', 'zerof'], ['nonbg_counts'], axis=1),
        helper.make_node('ArgMax', ['nonbg_counts'], ['rect_idx'], axis=1, keepdims=1, select_last_index=1),
        helper.make_node('Greater', ['nonbg_counts', 'zerof'], ['nonbg_present']),
        helper.make_node('ScatterElements', ['nonbg_present', 'rect_idx', 'bfalse'], ['marker_ch'], axis=1),
        helper.make_node('Cast', ['marker_ch'], ['marker_ohf'], to=1),
        helper.make_node('ScatterElements', ['marker_ohf', 'rect_idx', 'twof'], ['fg_w'], axis=1),
        helper.make_node('Conv', ['input', 'fg_w'], ['fg_f'], kernel_shape=[1, 1], pads=[0, 0, -6, -6]),
        helper.make_node('Cast', ['fg_f'], ['fg'], to=2),
        helper.make_node('MaxPool', ['fg'], ['rect_rows_u'], kernel_shape=[1, 24], pads=[0, 0, -1, 0], strides=[1, 1]),
        helper.make_node('Sub', ['rect_rows_u', 'uone'], ['rect_rows']),
        helper.make_node('MaxPool', ['fg'], ['rect_cols_u'], kernel_shape=[24, 1], pads=[0, 0, 0, -1], strides=[1, 1]),
        helper.make_node('Sub', ['rect_cols_u', 'uone'], ['rect_cols']),
        helper.make_node('Sub', ['uone', 'rect_rows'], ['nrows']),
        helper.make_node('Sub', ['uone', 'rect_cols'], ['ncols']),
        helper.make_node('MaxPool', ['fg'], ['fgL'], kernel_shape=[1, 24], pads=[0, 23, -1, -1], strides=[1, 1]),
        helper.make_node('MaxPool', ['fg'], ['fgR'], kernel_shape=[1, 24], pads=[0, 0, -1, 22], strides=[1, 1]),
        helper.make_node('MaxPool', ['fg'], ['fgU'], kernel_shape=[24, 1], pads=[23, 0, -1, -1], strides=[1, 1]),
        helper.make_node('MaxPool', ['fg'], ['fgD'], kernel_shape=[24, 1], pads=[0, 0, 22, -1], strides=[1, 1]),
        helper.make_node('Min', ['fgL', 'fgR', 'rect_rows', 'ncols'], ['hline']),
        helper.make_node('Min', ['fgU', 'fgD', 'rect_cols', 'nrows'], ['vline']),
        helper.make_node('Max', ['hline', 'vline'], ['line']),
        helper.make_node('Cast', ['line'], ['line_b'], to=9),
        helper.make_node('Pad', ['line_b', 'pads_hw', '', 'ax23'], ['line30'], mode='constant'),
        helper.make_node('Where', ['line30', 'marker_ohf', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task064_live_exact', nodes, inits, output_dtype=1, opset=20, value_infos=value_infos)
