"""Task 061 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('positions', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE4LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJCgsMDQ4PEBE=')),
        tensor('channel_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr+AAECAwQFBgcI')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAMAAAAAAAAAA==')),
        tensor('pad_value', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('q_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
    ]
    nodes = [
        helper.make_node('ReduceMax', ['input'], ['present'], axes=[2, 3], keepdims=0),
        helper.make_node('ArgMax', ['present'], ['mod_i64'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['mod_i64'], ['mod_u8'], to=2),
        helper.make_node('Mod', ['positions', 'mod_u8'], ['row_mod']),
        helper.make_node('Transpose', ['row_mod'], ['col_mod'], perm=[1, 0]),
        helper.make_node('QLinearMatMul', ['row_mod', 'q_scale', 'q_zero', 'col_mod', 'q_scale', 'q_zero', 'q_scale', 'q_zero'], ['product']),
        helper.make_node('Mod', ['product', 'mod_u8'], ['active_mod']),
        helper.make_node('Pad', ['active_mod', 'pads', 'pad_value'], ['full_mod'], mode='constant'),
        helper.make_node('Equal', ['full_mod', 'channel_ids'], ['output']),
    ]
    value_infos = [
    ]
    return model('task061_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
