"""Task 295 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ch_start', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('ch_end', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('black_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJ')),
        tensor('outside_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('zero_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAA==')),
        tensor('row_index', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDksIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEg=')),
        tensor('col_index', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDE4KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEw=')),
        tensor('half_f16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAOA==')),
        tensor('pad_spec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAAAMAAAAAAAAAA==')),
        tensor('channel_label_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAECAwQFBgcI')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input'], ['counts'], axes=[0, 2, 3], keepdims=0),
        helper.make_node('ReduceSum', ['counts'], ['width'], axes=[0], keepdims=0),
        helper.make_node('Slice', ['counts', 'ch_start', 'ch_end'], ['nz_counts']),
        helper.make_node('ReduceSum', ['nz_counts'], ['length'], axes=[0], keepdims=0),
        helper.make_node('ArgMax', ['nz_counts'], ['color_minus_one'], axis=0, keepdims=0),
        helper.make_node('Cast', ['color_minus_one'], ['color_u8'], to=2),
        helper.make_node('Cast', ['width'], ['width_f16'], to=10),
        helper.make_node('Mul', ['width_f16', 'half_f16'], ['half_width']),
        helper.make_node('Less', ['row_index', 'half_width'], ['in_height']),
        helper.make_node('Less', ['col_index', 'width_f16'], ['in_width']),
        helper.make_node('Cast', ['length'], ['length_f16'], to=10),
        helper.make_node('Add', ['row_index', 'length_f16'], ['fill_limit_raw']),
        helper.make_node('Where', ['in_height', 'fill_limit_raw', 'zero_f16'], ['fill_limit']),
        helper.make_node('Less', ['col_index', 'fill_limit'], ['filled']),
        helper.make_node('Where', ['in_height', 'black_u8', 'outside_u8'], ['row_default']),
        helper.make_node('Where', ['in_width', 'row_default', 'outside_u8'], ['default_label']),
        helper.make_node('Where', ['filled', 'color_u8', 'default_label'], ['small_label']),
        helper.make_node('Pad', ['small_label', 'pad_spec', 'outside_u8'], ['full_label'], mode='constant'),
        helper.make_node('Equal', ['full_label', 'channel_label_u8'], ['output']),
    ]
    value_infos = [
    ]
    return model('task295_live_exact', nodes, inits, output_dtype=9, opset=11, value_infos=value_infos)
