"""Task 159 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('slice_sizes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAwAAAAMAAAA=')),
        tensor('const_29_vec', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAodAAAA')),
        tensor('inv_ln4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAo7qjg/')),
        tensor('const_16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoQAAAA')),
        tensor('const_12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoMAAAA')),
        tensor('unsqueeze_axis0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('repeat_bank', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDE0KSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAEAAAACAAAAAwAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAMAAAAAAAAAAAAAAAEAAAABAAAAAgAAAAIAAAADAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAIAAAACAAAAAgAAAAMAAAAEAAAABAAAAAQAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAQAAAAEAAAACAAAAAgAAAAIAAAACAAAAAwAAAA==')),
        tensor('pad_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pad_patch', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('pad_output', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAA==')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('red_label_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('channel_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkK')),
        tensor('desc30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIBcAACAWwAAgFoAAIBZAACAWAAAgFcAAIBWAACAVQAAgFQAAIBTAACAUgAAgFEAAIBQAACATwAAgE4AAIBNAACATAAAgEsAAIBKAACASQAAgEgAAIBHAACARgAAgEUAAIBEAACAQwAAgEIAAIBBAACAQAAAgD8=')),
        tensor('motif_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/')),
        tensor('color_weights', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBB')),
        tensor('red_mask', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'motif_mask'], ['sprite_count'], equation='bcij,c->'),
        helper.make_node('Einsum', ['input', 'color_weights'], ['sprite_color_sum'], equation='bcij,c->'),
        helper.make_node('Div', ['sprite_color_sum', 'sprite_count'], ['sprite_channel_f']),
        helper.make_node('Cast', ['sprite_channel_f'], ['sprite_channel'], to=6),
        helper.make_node('Einsum', ['input', 'red_mask'], ['red_count_f'], equation='bcij,c->'),
        helper.make_node('Unsqueeze', ['sprite_channel', 'unsqueeze_axis0'], ['sprite_channel_vec']),
        helper.make_node('Einsum', ['input', 'motif_mask', 'desc30'], ['sprite_row_code'], equation='bcij,c,i->b'),
        helper.make_node('Einsum', ['input', 'motif_mask', 'desc30'], ['sprite_col_code'], equation='bcij,c,j->b'),
        helper.make_node('Log', ['sprite_row_code'], ['row_log']),
        helper.make_node('Log', ['sprite_col_code'], ['col_log']),
        helper.make_node('Mul', ['row_log', 'inv_ln4'], ['row_log4']),
        helper.make_node('Mul', ['col_log', 'inv_ln4'], ['col_log4']),
        helper.make_node('Cast', ['row_log4'], ['row_power_i32'], to=6),
        helper.make_node('Cast', ['col_log4'], ['col_power_i32'], to=6),
        helper.make_node('Sub', ['const_29_vec', 'row_power_i32'], ['top_i32']),
        helper.make_node('Sub', ['const_29_vec', 'col_power_i32'], ['left_i32']),
        helper.make_node('Concat', ['sprite_channel_vec', 'top_i32', 'left_i32'], ['slice_starts'], axis=0),
        helper.make_node('Add', ['slice_starts', 'slice_sizes'], ['slice_ends']),
        helper.make_node('Slice', ['input', 'slice_starts', 'slice_ends', 'slice_axes'], ['patch_selected']),
        helper.make_node('Cast', ['patch_selected'], ['patch_bool'], to=9),
        helper.make_node('Cast', ['sprite_channel'], ['sprite_channel_u8'], to=2),
        helper.make_node('Add', ['sprite_channel_u8', 'one_u8'], ['sprite_label_u8']),
        helper.make_node('Where', ['patch_bool', 'sprite_label_u8', 'one_u8'], ['patch_u8']),
        helper.make_node('Pad', ['patch_u8', 'pad_patch', 'red_label_u8', 'pad_axes'], ['patch4'], mode='constant'),
        helper.make_node('Pad', ['patch4', 'pad_patch', '', 'pad_axes'], ['patch5'], mode='constant'),
        helper.make_node('Cast', ['red_count_f'], ['red_count_i32'], to=6),
        helper.make_node('Sub', ['red_count_i32', 'const_16'], ['size_delta']),
        helper.make_node('Div', ['size_delta', 'const_12'], ['size_idx']),
        helper.make_node('Gather', ['repeat_bank', 'size_idx'], ['repeat_perm'], axis=0),
        helper.make_node('Gather', ['patch5', 'repeat_perm'], ['repeat_rows'], axis=2),
        helper.make_node('Gather', ['repeat_rows', 'repeat_perm'], ['target14'], axis=3),
        helper.make_node('Pad', ['target14', 'pad_output', '', 'pad_axes'], ['target30'], mode='constant'),
        helper.make_node('Equal', ['target30', 'channel_ids'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('patch_selected', 1, [1, 1, 3, 3]),
    ]
    return model('task159_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
