"""Task 109 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('diag_coords', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDQpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsAAAAAAAAACwAAAAAAAAA=')),
        tensor('fold_table', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsIDEyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAACAAAAAQAAAAAAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAAAAAAAQAAAAIAAAADAAAAAwAAAAIAAAABAAAAAAAAAAYAAAAGAAAABgAAAAYAAAAAAAAAAQAAAAIAAAADAAAABAAAAAQAAAADAAAAAgAAAAEAAAAAAAAABgAAAAYAAAAAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAFAAAABAAAAAMAAAACAAAAAQAAAAAAAAA=')),
        tensor('bg_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('bg_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAABgAAAAAAAAA=')),
        tensor('bg_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('f_half', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA/')),
        tensor('three', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
        tensor('one_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('zero_1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('L_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('one_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('bg9_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJ')),
        tensor('inv_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoK')),
        tensor('class_to_channel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJAAECAwQFBgcI')),
        tensor('pad18_pads_16_16', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('pad18_axes_16_17', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pad18_pads_19_18', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAASAAAAAAAAAA==')),
        tensor('axes_1_19', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('GatherND', ['input', 'diag_coords'], ['diag_f']),
        helper.make_node('ReduceSum', ['diag_f', 'axes_1_19'], ['case_f'], keepdims=0),
        helper.make_node('Cast', ['case_f'], ['case'], to=6),
        helper.make_node('Gather', ['fold_table', 'case'], ['rowfold'], axis=0),
        helper.make_node('Slice', ['input', 'bg_starts', 'bg_ends', 'bg_axes'], ['bg6f']),
        helper.make_node('Less', ['bg6f', 'f_half'], ['shp6']),
        helper.make_node('Add', ['case', 'three'], ['S_s']),
        helper.make_node('Unsqueeze', ['S_s', 'axes_1_19'], ['S_1']),
        helper.make_node('Add', ['S_1', 'one_1'], ['Sp1_1']),
        helper.make_node('Concat', ['zero_1', 'S_1'], ['Lstarts'], axis=0),
        helper.make_node('Concat', ['one_1', 'Sp1_1'], ['Lends'], axis=0),
        helper.make_node('Slice', ['input', 'Lstarts', 'Lends', 'L_axes'], ['Lwin']),
        helper.make_node('ArgMax', ['Lwin'], ['L'], axis=1, keepdims=1),
        helper.make_node('Sub', ['L', 'one_i64'], ['Lm1']),
        helper.make_node('Cast', ['Lm1'], ['Lm1_u8'], to=2),
        helper.make_node('Where', ['shp6', 'Lm1_u8', 'bg9_u8'], ['cls6']),
        helper.make_node('Pad', ['cls6', 'pad18_pads_16_16', 'inv_u8', 'pad18_axes_16_17'], ['cls7'], mode='constant'),
        helper.make_node('Gather', ['cls7', 'rowfold'], ['cls_rows'], axis=2),
        helper.make_node('Gather', ['cls_rows', 'rowfold'], ['class12'], axis=3),
        helper.make_node('Pad', ['class12', 'pad18_pads_19_18', 'inv_u8', 'pad18_axes_16_17'], ['class30'], mode='constant'),
        helper.make_node('Equal', ['class_to_channel', 'class30'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('Lwin', 1, [1, 10, 1, 1]),
    ]
    return model('task109_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
