"""Task 049 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('thr8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/AAAAAAAAAAAA')),
        tensor('big8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('ar30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA8AEAAQgBEAEUARgBHAEiASABJgEkASoBKAEuASwBMQEyATMBMAE1ATYBNwE0ATkBOgE7ATgBPQE8=')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input'], ['counts'], equation='ncrs->nc'),
        helper.make_node('Cast', ['counts'], ['counts8'], to=2),
        helper.make_node('Greater', ['counts8', 'thr8'], ['cond']),
        helper.make_node('Where', ['cond', 'counts8', 'big8'], ['masked']),
        helper.make_node('ReduceMin', ['masked'], ['area8'], axes=[1], keepdims=0),
        helper.make_node('Cast', ['area8'], ['area'], to=10),
        helper.make_node('Equal', ['masked', 'area8'], ['selb']),
        helper.make_node('Cast', ['selb'], ['self32'], to=1),
        helper.make_node('Einsum', ['input', 'self32', 'input', 'self32'], ['srsq'], equation='ncrs,nc,ndrt,nd->'),
        helper.make_node('Cast', ['srsq'], ['srsq16'], to=10),
        helper.make_node('Div', ['srsq16', 'area'], ['W']),
        helper.make_node('Div', ['area', 'W'], ['H']),
        helper.make_node('Cast', ['selb'], ['self16'], to=10),
        helper.make_node('Sub', ['H', 'ar30'], ['rmf']),
        helper.make_node('Less', ['ar30', 'W'], ['cmb']),
        helper.make_node('Cast', ['cmb'], ['cmf'], to=10),
        helper.make_node('Einsum', ['self16', 'rmf', 'cmf'], ['output'], equation='nc,r,s->ncrs'),
    ]
    value_infos = [
    ]
    return model('task049_live_exact', nodes, inits, output_dtype=10, opset=13, value_infos=value_infos)
