"""Task 094 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAADgAAAAAAAAAOAAAAAAAAAA==')),
        tensor('Wrow', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDEzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YmdPdmJnT3ZiZ092YmdPdmJnT3ZiZ092YmdPdmJnT3ZiZ092YmdPdmJnT3ZiZ092YmdPdmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT7ZiR0+2YkdPtmJHT4=')),
        tensor('Wcol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEzLCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIArZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT7ZiR0+2YmdPdmJHT4=')),
        tensor('thr', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqe2Mk/')),
        tensor('blue15_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAA')),
        tensor('zrow', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA=')),
        tensor('zcol', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAA=')),
        tensor('line30_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAA8AAAAAAAAA')),
        tensor('pink', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIA/AAAAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'starts', 'ends'], ['blue_f']),
        helper.make_node('Cast', ['blue_f'], ['blue_u8'], to=2),
        helper.make_node('Conv', ['blue_f', 'Wrow'], ['row_score'], dilations=[2, 1], kernel_shape=[3, 13]),
        helper.make_node('Conv', ['blue_f', 'Wcol'], ['col_score'], dilations=[1, 2], kernel_shape=[13, 3]),
        helper.make_node('Greater', ['row_score', 'thr'], ['row_b']),
        helper.make_node('Greater', ['col_score', 'thr'], ['col_b']),
        helper.make_node('Cast', ['row_b'], ['row9'], to=2),
        helper.make_node('Cast', ['col_b'], ['col9'], to=2),
        helper.make_node('Pad', ['blue_u8', 'blue15_pads'], ['blue15'], mode='constant'),
        helper.make_node('Concat', ['zrow', 'row9', 'zrow'], ['row15'], axis=2),
        helper.make_node('Concat', ['zcol', 'col9', 'zcol'], ['col15'], axis=3),
        helper.make_node('Max', ['row15', 'col15'], ['line_u8']),
        helper.make_node('Greater', ['line_u8', 'blue15'], ['line_bg15']),
        helper.make_node('Pad', ['line_bg15', 'line30_pads'], ['line_bg30'], mode='constant'),
        helper.make_node('Where', ['line_bg30', 'pink', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('blue_f', 1, [1, 1, 13, 13]),
        helper.make_tensor_value_info('blue_u8', 2, [1, 1, 13, 13]),
        helper.make_tensor_value_info('row_score', 1, [1, 1, 9, 1]),
        helper.make_tensor_value_info('col_score', 1, [1, 1, 1, 9]),
        helper.make_tensor_value_info('row_b', 9, [1, 1, 9, 1]),
        helper.make_tensor_value_info('col_b', 9, [1, 1, 1, 9]),
        helper.make_tensor_value_info('row9', 2, [1, 1, 9, 1]),
        helper.make_tensor_value_info('col9', 2, [1, 1, 1, 9]),
        helper.make_tensor_value_info('blue15', 2, [1, 1, 15, 15]),
        helper.make_tensor_value_info('row15', 2, [1, 1, 15, 1]),
        helper.make_tensor_value_info('col15', 2, [1, 1, 1, 15]),
        helper.make_tensor_value_info('line_u8', 2, [1, 1, 15, 15]),
        helper.make_tensor_value_info('line_bg15', 9, [1, 1, 15, 15]),
        helper.make_tensor_value_info('line_bg30', 9, [1, 1, 30, 30]),
    ]
    return model('task094_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
