"""Task 393 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('split', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAkAAAAAAAAA')),
        tensor('one', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('n144', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqQ')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAAB0AAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('ReduceL1', ['input'], ['cnt'], axes=[0, 2, 3], keepdims=1),
        helper.make_node('Cast', ['cnt'], ['cnt8'], to=2),
        helper.make_node('Split', ['cnt8', 'split'], ['c0', 'cnt9'], axis=1),
        helper.make_node('ReduceMax', ['cnt9'], ['a'], axes=[1], keepdims=1),
        helper.make_node('Sub', ['cnt9', 'one'], ['sh1']),
        helper.make_node('ReduceMin', ['sh1'], ['cm1'], axes=[1], keepdims=1),
        helper.make_node('Add', ['cm1', 'one'], ['c']),
        helper.make_node('Sub', ['n144', 'c0'], ['tot']),
        helper.make_node('Sub', ['tot', 'a'], ['ta']),
        helper.make_node('Sub', ['ta', 'c'], ['b']),
        helper.make_node('Concat', ['a', 'b', 'c'], ['valsr'], axis=2),
        helper.make_node('Equal', ['cnt9', 'valsr'], ['small']),
        helper.make_node('Pad', ['small', 'pads'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task393_live_exact', nodes, inits, output_dtype=9, opset=14, value_infos=value_infos)
