"""Task 019 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sl_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('sl_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAABgAAAAAAAAA=')),
        tensor('sl_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('zerof', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('ar12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEyLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAAAAsAAAA=')),
        tensor('ar12r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEyLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEE=')),
        tensor('ar12c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDEyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEE=')),
        tensor('ar10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('zeru8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('sentinel', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApj')),
        tensor('qker', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEB')),
        tensor('qs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('ys', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqBgIA7')),
        tensor('padamt', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAABIAAAAAAAAA')),
        tensor('coltab', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGB/8J')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'sl_starts', 'sl_ends', 'sl_axes'], ['bg6']),
        helper.make_node('Equal', ['bg6', 'zerof'], ['colored_fund']),
        helper.make_node('ReduceSum', ['bg6'], ['rowsum'], keepdims=1, axes=[3]),
        helper.make_node('Sign', ['rowsum'], ['rowsign']),
        helper.make_node('ReduceSum', ['rowsign'], ['Hf'], keepdims=1, axes=[2, 3]),
        helper.make_node('ReduceMax', ['rowsum'], ['Wf'], axes=[2, 3], keepdims=1),
        helper.make_node('Add', ['Hf', 'Hf'], ['twoH']),
        helper.make_node('Add', ['Wf', 'Wf'], ['twoW']),
        helper.make_node('Cast', ['Hf'], ['Hi'], to=6),
        helper.make_node('Squeeze', ['Hi'], ['Hs'], axes=[0, 1, 2, 3]),
        helper.make_node('Cast', ['Wf'], ['Wi'], to=6),
        helper.make_node('Squeeze', ['Wi'], ['Ws'], axes=[0, 1, 2, 3]),
        helper.make_node('Mod', ['ar12', 'Hs'], ['rowidx']),
        helper.make_node('Mod', ['ar12', 'Ws'], ['colidx']),
        helper.make_node('Gather', ['colored_fund', 'rowidx'], ['Mrow'], axis=2),
        helper.make_node('Gather', ['Mrow', 'colidx'], ['Mtile'], axis=3),
        helper.make_node('Less', ['ar12r', 'twoH'], ['rowlt']),
        helper.make_node('Less', ['ar12c', 'twoW'], ['collt']),
        helper.make_node('And', ['rowlt', 'collt'], ['rect']),
        helper.make_node('And', ['Mtile', 'rect'], ['Mmask']),
        helper.make_node('Cast', ['Mmask'], ['MmaskU8'], to=2),
        helper.make_node('QLinearConv', ['MmaskU8', 'qs', 'zeru8', 'qker', 'qs', 'zeru8', 'ys', 'zeru8'], ['dil'], dilations=[2, 2], kernel_shape=[2, 2], pads=[1, 1, 1, 1]),
        helper.make_node('ReduceMax', ['input'], ['chmax'], axes=[2, 3], keepdims=1),
        helper.make_node('Cast', ['chmax'], ['present'], to=9),
        helper.make_node('Where', ['present', 'ar10', 'zeru8'], ['Vsel']),
        helper.make_node('ReduceMax', ['Vsel'], ['Vu8'], axes=[1], keepdims=1),
        helper.make_node('Where', ['Mmask', 'Vu8', 'dil'], ['idxc']),
        helper.make_node('Where', ['rect', 'idxc', 'sentinel'], ['idxs']),
        helper.make_node('Pad', ['idxs', 'padamt', 'sentinel'], ['idx30'], mode='constant'),
        helper.make_node('Equal', ['idx30', 'coltab'], ['output']),
    ]
    value_infos = [
    ]
    return model('task019_live_exact', nodes, inits, output_dtype=9, opset=12, value_infos=value_infos)
