"""Task 394 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('ch0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('idx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAEAAAEBAAACAQAAAoEAAAMBAAADgQAAAAEEAABBBAAAgQQAAMEEAAEBBAABQQQAAYEEAAHBBAACAQQAAiEEAAJBBAACYQQAAoEEAAKhBAACwQQAAuEEAAMBBAADIQQAA0EEAANhBAADgQQAA6EE=')),
        tensor('off_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQI=')),
        tensor('off_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQI=')),
        tensor('c2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('c3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('c36', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAABBC')),
        tensor('dq_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGYyJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAqSLA==')),
        tensor('c14', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoO')),
        tensor('xy', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGIxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAA==')),
        tensor('pad_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAGwAAAAAAAAAbAAAAAAAAAA==')),
        tensor('pad_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'ch0'], ['N2f'], equation='nchw,c->'),
        helper.make_node('Einsum', ['input', 'ch0', 'idx'], ['row_sum'], equation='nchw,c,h->'),
        helper.make_node('Einsum', ['input', 'ch0', 'idx'], ['col_sum'], equation='nchw,c,w->'),
        helper.make_node('ReduceSum', ['input'], ['area'], keepdims=0),
        helper.make_node('Cast', ['N2f'], ['N2u'], to=2),
        helper.make_node('Cast', ['row_sum'], ['rs_u'], to=2),
        helper.make_node('Cast', ['col_sum'], ['cs_u'], to=2),
        helper.make_node('BitShift', ['N2u', 'c3'], ['corr'], direction='RIGHT'),
        helper.make_node('Div', ['rs_u', 'N2u'], ['r0pre']),
        helper.make_node('Div', ['cs_u', 'N2u'], ['c0pre']),
        helper.make_node('Sub', ['r0pre', 'corr'], ['r0']),
        helper.make_node('Sub', ['c0pre', 'corr'], ['c0']),
        helper.make_node('Greater', ['area', 'c36'], ['wide']),
        helper.make_node('Where', ['wide', 'c3', 'c2'], ['P']),
        helper.make_node('Add', ['P', 'P'], ['twoP']),
        helper.make_node('Add', ['r0', 'P'], ['rowbase']),
        helper.make_node('Add', ['rowbase', 'off_r'], ['row_pp']),
        helper.make_node('Mod', ['row_pp', 'twoP'], ['src_row0']),
        helper.make_node('Add', ['c0', 'off_c'], ['src_col0']),
        helper.make_node('Add', ['off_r', 'off_r'], ['off2']),
        helper.make_node('Less', ['off2', 'N2u'], ['validr']),
        helper.make_node('Transpose', ['validr'], ['validc'], perm=[1, 0, 2]),
        helper.make_node('Where', ['validr', 'src_row0', 'c14'], ['src_row']),
        helper.make_node('Where', ['validc', 'src_col0', 'c14'], ['src_col']),
        helper.make_node('DequantizeLinear', ['src_row', 'dq_scale', 'c14'], ['row_norm']),
        helper.make_node('DequantizeLinear', ['src_col', 'dq_scale', 'c14'], ['col_norm']),
        helper.make_node('Where', ['xy', 'col_norm', 'row_norm'], ['grid']),
        helper.make_node('GridSample', ['input', 'grid'], ['block'], align_corners=1, mode='nearest', padding_mode='zeros'),
        helper.make_node('Pad', ['block', 'pad_hw', '', 'pad_axes'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task394_live_exact', nodes, inits, output_dtype=1, opset=20, value_infos=value_infos)
