"""Task 330 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('crop_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('crop_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAYAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('blk', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEwLCAxMCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoGBgEBBQUICAICBgYBAQUFCAgCAgEBBQUCAgICAQEBAQUFAgICAgEBBwcAAAAAAAABAQcHAAAAAAAAAQEAAAAABAQAAAEBAAAAAAQEAAABAQAAAwMAAAkJAQEAAAMDAAAJCQEB')),
        tensor('ones2x2_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDIsIDIpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEB')),
        tensor('q_scale', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('q_zero', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('hist0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAA')),
        tensor('one_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('six_u', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoG')),
        tensor('shp55', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoFAAAAAAAAAAUAAAAAAAAA')),
        tensor('scales', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABAAAAAQA==')),
        tensor('chan3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDMsIDEsIDEpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQY=')),
        tensor('pad_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAUAAAAAAAAABQAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'crop_s', 'crop_e'], ['mask_f']),
        helper.make_node('Cast', ['mask_f'], ['mask_u'], to=2),
        helper.make_node('Mul', ['mask_u', 'blk'], ['lab0']),
        helper.make_node('MaxPool', ['lab0'], ['pool0'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Mul', ['pool0', 'mask_u'], ['lab1']),
        helper.make_node('MaxPool', ['lab1'], ['pool1'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Mul', ['pool1', 'mask_u'], ['lab2']),
        helper.make_node('MaxPool', ['lab2'], ['pool2'], kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]),
        helper.make_node('Mul', ['pool2', 'mask_u'], ['lab3']),
        helper.make_node('MaxPool', ['lab3'], ['blk_lab'], kernel_shape=[2, 2], strides=[2, 2]),
        helper.make_node('QLinearConv', ['mask_u', 'q_scale', 'q_zero', 'ones2x2_u', 'q_scale', 'q_zero', 'q_scale', 'q_zero'], ['blk_cnt'], kernel_shape=[2, 2], strides=[2, 2]),
        helper.make_node('Flatten', ['blk_lab'], ['lab_flat'], axis=1),
        helper.make_node('Cast', ['lab_flat'], ['idx'], to=6),
        helper.make_node('Flatten', ['blk_cnt'], ['cnt_flat'], axis=1),
        helper.make_node('ScatterElements', ['hist0', 'idx', 'cnt_flat'], ['hist'], axis=1, reduction='add'),
        helper.make_node('Equal', ['hist', 'six_u'], ['is6']),
        helper.make_node('Where', ['is6', 'six_u', 'one_u'], ['color_lab']),
        helper.make_node('GatherElements', ['color_lab', 'idx'], ['blk_color'], axis=1),
        helper.make_node('Reshape', ['blk_color', 'shp55'], ['blk_color2d']),
        helper.make_node('Resize', ['blk_color2d', '', 'scales'], ['color_up'], coordinate_transformation_mode='asymmetric', mode='nearest', nearest_mode='floor'),
        helper.make_node('Mul', ['mask_u', 'color_up'], ['V']),
        helper.make_node('Equal', ['V', 'chan3'], ['out3']),
        helper.make_node('Pad', ['out3', 'pad_pads'], ['output'], mode='constant'),
    ]
    value_infos = [
    ]
    return model('task330_live_exact', nodes, inits, output_dtype=9, opset=17, value_infos=value_infos)
