"""Task 301 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('axes_hw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('one_i64', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('row_plus1_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEyLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAkKCww=')),
        tensor('col_plus1_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDkpLCB9ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAgMEBQYHCAk=')),
        tensor('b0_thresholds', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDEsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApkZWZnaGlqa2z///////////////////////////8=')),
        tensor('offset100_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApk')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('high_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('slice_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAAAAAAAA==')),
        tensor('pad_a_short', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAABIAAAAAAAAA')),
        tensor('pad_b_short', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAABUAAAAAAAAA')),
        tensor('pad_axis_h', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('pad_axis_w', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('ReduceSum', ['input', 'axes_hw'], ['color_counts_f'], keepdims=1),
        helper.make_node('Cast', ['color_counts_f'], ['color_counts_u8'], to=2),
        helper.make_node('Slice', ['color_counts_u8', 'one_i64', 'slice_ends', 'one_i64'], ['counts_nonbg']),
        helper.make_node('ReduceMax', ['counts_nonbg', 'one_i64'], ['width_u8'], keepdims=1),
        helper.make_node('ReduceSum', ['color_counts_f', 'one_i64'], ['total_area_f'], keepdims=1),
        helper.make_node('Cast', ['total_area_f'], ['total_area_u8'], to=2),
        helper.make_node('Div', ['total_area_u8', 'width_u8'], ['height_u8']),
        helper.make_node('Sub', ['height_u8', 'width_u8'], ['gap_u8']),
        helper.make_node('Sub', ['width_u8', 'col_plus1_u8'], ['bcolor']),
        helper.make_node('Pad', ['bcolor', 'pad_b_short', 'high_u8', 'pad_axis_w'], ['bcolor_thresholds'], mode='constant'),
        helper.make_node('Concat', ['b0_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds', 'bcolor_thresholds'], ['b_thresholds'], axis=1),
        helper.make_node('Add', ['height_u8', 'offset100_u8'], ['height_offset']),
        helper.make_node('Sub', ['height_offset', 'row_plus1_u8'], ['a0_uncapped']),
        helper.make_node('Add', ['width_u8', 'offset100_u8'], ['width_limit']),
        helper.make_node('Min', ['a0_uncapped', 'width_limit'], ['a0']),
        helper.make_node('Add', ['gap_u8', 'counts_nonbg'], ['target_plus1_u8']),
        helper.make_node('Equal', ['row_plus1_u8', 'target_plus1_u8'], ['row_eq']),
        helper.make_node('Where', ['row_eq', 'counts_nonbg', 'zero_u8'], ['acolor']),
        helper.make_node('Concat', ['a0', 'acolor'], ['a_compact'], axis=1),
        helper.make_node('Pad', ['a_compact', 'pad_a_short', '', 'pad_axis_h'], ['a_thresholds'], mode='constant'),
        helper.make_node('Greater', ['a_thresholds', 'b_thresholds'], ['output']),
    ]
    value_infos = [
    ]
    return model('task301_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
