"""Task 086 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('w_collapse', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAQAAAQEAAAIBAAACgQAAAwEAAAOBAAAAAQQAAEEEAACBB')),
        tensor('b_collapse', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIC/')),
        tensor('zero_f', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA')),
        tensor('karm', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEsIDExLCAxMSksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoEAQcHCg0KBwcBBAH7Cf378/v9CfsBBwn+/fkS+f3+CQcH/f0FDR8NBf39Bwr7+Q0cLBwN+fsKDfMSHywALB8S8w0K+/kNHCwcDfn7Cgf9/QUNHw0F/f0HBwn+/fkS+f3+CQcB+wn9+/P7/Qn7AQQBBwcKDQoHBwEE')),
        tensor('xs', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/')),
        tensor('xz', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('barm', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAq0////')),
        tensor('k3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('i1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA==')),
        tensor('i2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('c255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('pad30', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAABIAAAAAAAAA')),
        tensor('chan_ids', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'w_collapse', 'b_collapse'], ['Lin'], kernel_shape=[1, 1], pads=[0, 0, -18, -18]),
        helper.make_node('Greater', ['Lin', 'zero_f'], ['Fb']),
        helper.make_node('Cast', ['Fb'], ['F8'], to=3),
        helper.make_node('Cast', ['Lin'], ['base'], to=2),
        helper.make_node('QLinearConv', ['F8', 'xs', 'xz', 'karm', 'xs', 'xz', 'xs', 'xz', 'barm'], ['q'], pads=[5, 5, 5, 5]),
        helper.make_node('Greater', ['q', 'xz'], ['vh']),
        helper.make_node('GlobalAveragePool', ['input'], ['cnt']),
        helper.make_node('TopK', ['cnt', 'k3'], ['tv', 'ti'], axis=1),
        helper.make_node('Gather', ['ti', 'i1'], ['c1i'], axis=1),
        helper.make_node('Gather', ['ti', 'i2'], ['c0i'], axis=1),
        helper.make_node('Cast', ['c1i'], ['c1_u8'], to=2),
        helper.make_node('Cast', ['c0i'], ['c0_u8'], to=2),
        helper.make_node('Cast', ['c0i'], ['c0_f'], to=1),
        helper.make_node('Equal', ['Lin', 'c0_f'], ['inner']),
        helper.make_node('Where', ['inner', 'c1_u8', 'c0_u8'], ['inner_ch']),
        helper.make_node('Where', ['vh', 'c1_u8', 'base'], ['outer_ch']),
        helper.make_node('Where', ['Fb', 'inner_ch', 'outer_ch'], ['label']),
        helper.make_node('Pad', ['label', 'pad30', 'c255'], ['label30'], mode='constant'),
        helper.make_node('Equal', ['label30', 'chan_ids'], ['output']),
    ]
    value_infos = [
    ]
    return model('task086_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
