"""Task 004 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('Wc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAyLCAyKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIDDAAAAAAAAAAAAAAAAAAB/wwAAAAAAAAAAAAAAAAAAfsMAAAAAAAAAAAAAAAAAAH3DAAAAAAAAAAAAAAAAAAB8wwAAAAAAAAAAAAAAAAAAe8MAAAAAAAAAAAAAAAAAAHrDAAAAAAAAAAAAAAAAAAB5wwAAAAAAAAAAAAAAAAAAeMMAAAAAAAAAAAAAAAAAAHfDAAAAAAAAAAAAAAAA')),
        tensor('bc', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIBD')),
        tensor('bidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAAAAAAAAsAAAAAAAAADAAAAAAAAAANAAAAAAAAAA4AAAAAAAAADwAAAAAAAAAAAAAAAAAAAA==')),
        tensor('sidx', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE2LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoPAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAACgAAAAAAAAALAAAAAAAAAAwAAAAAAAAADQAAAAAAAAAOAAAAAAAAAA==')),
        tensor('pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAA4AAAAAAAAA')),
        tensor('palette', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('u0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('u255', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('f128', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAABD')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'Wc', 'bc'], ['code_f'], dilations=[14, 14], kernel_shape=[2, 2], pads=[0, 0, 0, 0]),
        helper.make_node('Less', ['code_f', 'f128'], ['valid']),
        helper.make_node('Cast', ['code_f'], ['vals'], to=2),
        helper.make_node('Gather', ['vals', 'bidx'], ['below'], axis=2),
        helper.make_node('Gather', ['vals', 'bidx'], ['right'], axis=3),
        helper.make_node('ReduceMax', ['below'], ['row_next'], axes=[3], keepdims=1),
        helper.make_node('Cast', ['row_next'], ['row_next_b'], to=9),
        helper.make_node('Greater', ['below', 'right'], ['endpoint']),
        helper.make_node('Xor', ['row_next_b', 'endpoint'], ['move']),
        helper.make_node('Where', ['move', 'vals', 'u0'], ['move_vals']),
        helper.make_node('Gather', ['move_vals', 'sidx'], ['shifted'], axis=3),
        helper.make_node('Where', ['move', 'u0', 'vals'], ['stay']),
        helper.make_node('Max', ['stay', 'shifted'], ['scalar_out']),
        helper.make_node('Where', ['valid', 'scalar_out', 'u255'], ['scalar_valid']),
        helper.make_node('Pad', ['scalar_valid', 'pads', 'u255'], ['scalar_full'], mode='constant'),
        helper.make_node('Equal', ['scalar_full', 'palette'], ['output']),
    ]
    value_infos = [
    ]
    return model('task004_live_exact', nodes, inits, output_dtype=9, opset=13, value_infos=value_infos)
