"""Task 129 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
    ]
    nodes = [
        helper.make_node('GlobalAveragePool', ['input'], ['counts']),
        helper.make_node('Hardmax', ['counts'], ['winner'], axis=1),
        helper.make_node('Einsum', ['winner', 'input'], ['output'], equation='bcxy,bdhw->bchw'),
    ]
    value_infos = [
    ]
    return model('task129_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
