"""Task 062 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('false_base_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoIAAAA')),
        tensor('one_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('neg_one_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/////')),
        tensor('offset_minus_id_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDgsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAA//////7////9/////P////v////6////+f///w==')),
        tensor('zero_scalar_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('green_scalar_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('clear_scalar_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAr/')),
        tensor('selector_ids_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQADBAUGBwgJ')),
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAA=')),
        tensor('slice_black_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('slice_black_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAkAAAAAAAAACQAAAAAAAAA=')),
        tensor('slice_red_starts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAA=')),
        tensor('slice_red_ends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAAkAAAAAAAAACQAAAAAAAAA=')),
        tensor('pad18_pads_33_17', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAIAAAAAAAAA')),
        tensor('pad18_axes_33_18', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAAAAAAAA==')),
        tensor('pad18_axes_34_19', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAA==')),
        tensor('pad18_pads_40_20', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAA==')),
        tensor('pad18_axes_40_21', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAAAAAAMAAAAAAAAA')),
        tensor('pad18_pads_41_22', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('axes_7_24', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAA=')),
        tensor('axes_10_25', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAwAAAAAAAAA=')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'slice_black_starts', 'slice_black_ends', 'slice_axes'], ['black_f']),
        helper.make_node('Slice', ['input', 'slice_red_starts', 'slice_red_ends', 'slice_axes'], ['red_f']),
        helper.make_node('Equal', ['black_f', 'red_f'], ['obj_any']),
        helper.make_node('ReduceMax', ['input', 'pad18_axes_40_21'], ['present10_f'], keepdims=1),
        helper.make_node('Cast', ['present10_f'], ['present10_b'], to=9),
        helper.make_node('Where', ['present10_b', 'selector_ids_u8', 'zero_scalar_u8'], ['present_color_u8']),
        helper.make_node('ReduceMax', ['present_color_u8'], ['obj_color_u8'], keepdims=0),
        helper.make_node('ReduceMax', ['red_f', 'axes_7_24'], ['marker_col_occ'], keepdims=0),
        helper.make_node('ArgMax', ['marker_col_occ'], ['axis_col_raw'], axis=0, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['axis_col_raw'], ['axis_col'], to=6),
        helper.make_node('ReduceMax', ['red_f', 'axes_10_25'], ['marker_row_occ'], keepdims=0),
        helper.make_node('ArgMax', ['marker_row_occ'], ['axis_row_raw'], axis=0, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['axis_row_raw'], ['axis_row'], to=6),
        helper.make_node('Cast', ['obj_any'], ['obj_u8'], to=2),
        helper.make_node('ReduceMax', ['obj_u8', 'axes_7_24'], ['obj_col_occ'], keepdims=0),
        helper.make_node('ArgMax', ['obj_col_occ'], ['max_col'], axis=0, keepdims=0, select_last_index=1),
        helper.make_node('ArgMax', ['obj_col_occ'], ['min_col'], axis=0, keepdims=0, select_last_index=0),
        helper.make_node('ReduceMax', ['obj_u8', 'axes_10_25'], ['obj_row_occ'], keepdims=0),
        helper.make_node('ArgMax', ['obj_row_occ'], ['min_row'], axis=0, keepdims=0, select_last_index=0),
        helper.make_node('Greater', ['min_col', 'axis_col_raw'], ['sel_r_b']),
        helper.make_node('Less', ['max_col', 'axis_col_raw'], ['sel_l_b']),
        helper.make_node('Greater', ['min_row', 'axis_row_raw'], ['sel_d_b']),
        helper.make_node('Or', ['sel_r_b', 'sel_l_b'], ['sel_h']),
        helper.make_node('Add', ['axis_col', 'axis_col'], ['axis_col2']),
        helper.make_node('Add', ['axis_row', 'axis_row'], ['axis_row2']),
        helper.make_node('Where', ['sel_r_b', 'one_i32', 'neg_one_i32'], ['delta_h']),
        helper.make_node('Where', ['sel_d_b', 'one_i32', 'neg_one_i32'], ['delta_v']),
        helper.make_node('Add', ['axis_col2', 'delta_h'], ['base_h_raw']),
        helper.make_node('Add', ['axis_row2', 'delta_v'], ['base_v_raw']),
        helper.make_node('Add', ['base_h_raw', 'offset_minus_id_i32'], ['idx_h_raw']),
        helper.make_node('Add', ['base_v_raw', 'offset_minus_id_i32'], ['idx_v_raw']),
        helper.make_node('Where', ['sel_h', 'idx_h_raw', 'false_base_i32'], ['idx_h_pad']),
        helper.make_node('Where', ['sel_h', 'false_base_i32', 'idx_v_raw'], ['idx_v_pad']),
        helper.make_node('Pad', ['obj_any', 'pad18_pads_33_17', '', 'pad18_axes_33_18'], ['obj_pad_h'], mode='constant'),
        helper.make_node('Pad', ['obj_any', 'pad18_pads_33_17', '', 'pad18_axes_34_19'], ['obj_pad_v'], mode='constant'),
        helper.make_node('Gather', ['obj_pad_h', 'idx_h_pad'], ['ref_h_raw'], axis=3),
        helper.make_node('Gather', ['obj_pad_v', 'idx_v_pad'], ['ref_v_raw'], axis=2),
        helper.make_node('Or', ['ref_h_raw', 'ref_v_raw'], ['ref']),
        helper.make_node('Or', ['obj_any', 'ref'], ['obj_all']),
        helper.make_node('Where', ['obj_all', 'obj_color_u8', 'green_scalar_u8'], ['color_grid8']),
        helper.make_node('Pad', ['color_grid8', 'pad18_pads_40_20', 'green_scalar_u8', 'pad18_axes_40_21'], ['color_grid10'], mode='constant'),
        helper.make_node('Pad', ['color_grid10', 'pad18_pads_41_22', 'clear_scalar_u8', 'pad18_axes_40_21'], ['color_grid30'], mode='constant'),
        helper.make_node('Equal', ['color_grid30', 'selector_ids_u8'], ['output']),
    ]
    value_infos = [
    ]
    return model('task062_live_exact', nodes, inits, output_dtype=9, opset=18, value_infos=value_infos)
