"""Task 332 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('D', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAIA/AAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('C', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsIDMwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/CteDvwAAgD8K14O/AACAPwrXg78AAIA/CteDvwAAgD8K14O/AACAPwrXg78AAIA/CteDvwAAgD8K14O/AACAPwrXg78AAIA/CteDvwAAgD8K14O/AACAPwrXg78AAIA/CteDvwAAgD8K14O/AACAPwrXg78=')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'input', 'D', 'D', 'D', 'C', 'C'], ['output'], equation='nihw,njru,ti,to,tk,tw,tu->nohw'),
    ]
    value_infos = [
    ]
    return model('task332_live_exact', nodes, inits, output_dtype=1, opset=13, value_infos=value_infos)
