"""Task 263 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('W', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwLCAzLCAzKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAIA/AACAPwAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')),
        tensor('z', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('o3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoD')),
        tensor('o6', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoG')),
        tensor('o9', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoJ')),
        tensor('o12', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoM')),
        tensor('slice_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
        tensor('span3', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoDAAAA')),
    ]
    nodes = [
        helper.make_node('Conv', ['input', 'W'], ['h4f'], kernel_shape=[3, 3], pads=[0, 0, -27, -18], strides=[3, 3]),
        helper.make_node('Conv', ['input', 'W'], ['v3f'], kernel_shape=[3, 3], pads=[-3, 0, -18, -27], strides=[3, 3]),
        helper.make_node('Cast', ['h4f'], ['h4'], to=2),
        helper.make_node('Cast', ['v3f'], ['v3s'], to=2),
        helper.make_node('Split', ['h4'], ['h0', 'h1', 'h2', 'h3'], axis=3),
        helper.make_node('Split', ['v3s'], ['v1', 'v2', 'v3'], axis=2),
        helper.make_node('Cast', ['v1'], ['is_vertical_raw'], to=9),
        helper.make_node('Where', ['is_vertical_raw', 'v1', 'h1'], ['s1']),
        helper.make_node('Where', ['is_vertical_raw', 'v2', 'h2'], ['s2']),
        helper.make_node('Where', ['is_vertical_raw', 'v3', 'h3'], ['s3']),
        helper.make_node('Squeeze', ['is_vertical_raw'], ['is_vertical'], axes=[0, 1, 2]),
        helper.make_node('Less', ['h0', 's1'], ['lt01a']),
        helper.make_node('Less', ['s1', 'h0'], ['lt01b']),
        helper.make_node('Or', ['lt01a', 'lt01b'], ['d01']),
        helper.make_node('Less', ['h0', 's2'], ['lt02a']),
        helper.make_node('Less', ['s2', 'h0'], ['lt02b']),
        helper.make_node('Or', ['lt02a', 'lt02b'], ['d02']),
        helper.make_node('Less', ['h0', 's3'], ['lt03a']),
        helper.make_node('Less', ['s3', 'h0'], ['lt03b']),
        helper.make_node('Or', ['lt03a', 'lt03b'], ['d03']),
        helper.make_node('Where', ['d02', 'z', 'o3'], ['off_if_d01']),
        helper.make_node('Where', ['d03', 'o9', 'o12'], ['off_tail']),
        helper.make_node('Where', ['d02', 'o6', 'off_tail'], ['off_if_not_d01']),
        helper.make_node('Where', ['d01', 'off_if_d01', 'off_if_not_d01'], ['off_raw']),
        helper.make_node('Squeeze', ['off_raw'], ['off'], axes=[0, 1, 2]),
        helper.make_node('Where', ['is_vertical', 'off', 'z'], ['row']),
        helper.make_node('Where', ['is_vertical', 'z', 'off'], ['col']),
        helper.make_node('Concat', ['row', 'col'], ['starts_u8'], axis=0),
        helper.make_node('Cast', ['starts_u8'], ['starts'], to=6),
        helper.make_node('Add', ['starts', 'span3'], ['ends']),
        helper.make_node('Slice', ['input', 'starts', 'ends', 'slice_axes'], ['out3']),
        helper.make_node('Pad', ['out3'], ['output'], mode='constant', pads=[0, 0, 0, 0, 0, 0, 27, 27]),
    ]
    value_infos = [
        helper.make_tensor_value_info('out3', 1, [1, 10, 3, 3]),
    ]
    return model('task263_live_exact', nodes, inits, output_dtype=1, opset=10, value_infos=value_infos)
