"""Task 190 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('bstarts', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAgAAAAIAAAA=')),
        tensor('bends', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAACAAAAAgAAAA=')),
        tensor('zero_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('one_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('two_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('big_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApk')),
        tensor('R_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('C_u8', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsIDEwKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJ')),
        tensor('out_pads', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAUAAAAAAAAAA==')),
        tensor('one_i32', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAA')),
        tensor('patch_size', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAABAAAAAQAAAA=')),
        tensor('patch_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAgAAAAMAAAA=')),
        tensor('patch_steps', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAwAAAAMAAAA=')),
        tensor('spatial_axes', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoCAAAAAwAAAA==')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'bstarts', 'bends', 'patch_axes'], ['bg_f']),
        helper.make_node('Cast', ['bg_f'], ['bg_u8'], to=2),
        helper.make_node('MaxPool', ['bg_u8'], ['blockmax'], kernel_shape=[2, 2]),
        helper.make_node('ReduceMin', ['blockmax'], ['rowmin'], axes=[0, 1, 3], keepdims=0),
        helper.make_node('ReduceMin', ['blockmax'], ['colmin'], axes=[0, 1, 2], keepdims=0),
        helper.make_node('ArgMin', ['rowmin'], ['br_s'], axis=0, keepdims=1),
        helper.make_node('ArgMin', ['colmin'], ['bc_s'], axis=0, keepdims=1),
        helper.make_node('Cast', ['br_s'], ['br_u8'], to=2),
        helper.make_node('Cast', ['bc_s'], ['bc_u8'], to=2),
        helper.make_node('Sub', ['br_u8', 'bc_u8'], ['diag0']),
        helper.make_node('Add', ['br_u8', 'one_u8'], ['row_st']),
        helper.make_node('Add', ['bc_u8', 'one_u8'], ['col_st']),
        helper.make_node('Add', ['row_st', 'two_u8'], ['brp1']),
        helper.make_node('Add', ['bc_u8', 'two_u8'], ['bc_full']),
        helper.make_node('Add', ['brp1', 'bc_full'], ['anti0']),
        helper.make_node('Less', ['R_u8', 'brp1'], ['north']),
        helper.make_node('Concat', ['zero_u8', 'row_st', 'col_st'], ['pstarts_u8'], axis=0),
        helper.make_node('Cast', ['pstarts_u8'], ['pstarts'], to=6),
        helper.make_node('Add', ['pstarts', 'patch_size'], ['pends']),
        helper.make_node('Slice', ['input', 'pstarts', 'pends', 'patch_axes', 'patch_steps'], ['seed_f']),
        helper.make_node('Cast', ['seed_f'], ['seed_b'], to=9),
        helper.make_node('Where', ['seed_b', 'big_u8', 'zero_u8'], ['seed_off']),
        helper.make_node('Flatten', ['seed_off'], ['seed_v'], axis=0),
        helper.make_node('Split', ['seed_v'], ['o_nw', 'o_ne', 'o_sw', 'o_se'], axis=1),
        helper.make_node('Sub', ['o_nw', 'diag0'], ['m_nw']),
        helper.make_node('Sub', ['o_se', 'diag0'], ['m_se']),
        helper.make_node('Add', ['o_ne', 'anti0'], ['m_ne']),
        helper.make_node('Add', ['o_sw', 'anti0'], ['m_sw']),
        helper.make_node('Where', ['north', 'm_nw', 'm_se'], ['diag_adj']),
        helper.make_node('Where', ['north', 'm_ne', 'm_sw'], ['anti_adj']),
        helper.make_node('Add', ['R_u8', 'diag_adj'], ['diag_pick']),
        helper.make_node('Sub', ['anti_adj', 'R_u8'], ['anti_pick']),
        helper.make_node('Equal', ['C_u8', 'diag_pick'], ['diag_rays']),
        helper.make_node('Equal', ['C_u8', 'anti_pick'], ['anti_rays']),
        helper.make_node('Or', ['diag_rays', 'anti_rays'], ['mask']),
        helper.make_node('Concat', ['brp1', 'bc_full'], ['cstarts_u8'], axis=0),
        helper.make_node('Cast', ['cstarts_u8'], ['cstarts'], to=6),
        helper.make_node('Add', ['cstarts', 'one_i32'], ['cends']),
        helper.make_node('Slice', ['input', 'cstarts', 'cends', 'spatial_axes'], ['color_vec']),
        helper.make_node('Pad', ['mask', 'out_pads'], ['mask30'], mode='constant'),
        helper.make_node('Where', ['mask30', 'color_vec', 'input'], ['output']),
    ]
    value_infos = [
        helper.make_tensor_value_info('seed_f', 1, [1, 1, 2, 2]),
        helper.make_tensor_value_info('color_vec', 1, [1, 10, 1, 1]),
    ]
    return model('task190_live_exact', nodes, inits, output_dtype=1, opset=14, value_infos=value_infos)
