"""Task 224 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('guide', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAgD8AAIA/AACAPwAAgL8AAIA/AACAPwAAgD8AAIA/')),
        tensor('u0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoA')),
        tensor('u1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB')),
        tensor('u2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoC')),
        tensor('idx_r', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE0LCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJCgsMDQ==')),
        tensor('idx_c', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDE0LCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAQIDBAUGBwgJCgsMDQ==')),
        tensor('pad_span', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAA8AAAAAAAAA')),
        tensor('axis0', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAA==')),
    ]
    nodes = [
        helper.make_node('Einsum', ['input', 'guide'], ['row_score'], equation='nchw,cab->nh'),
        helper.make_node('Einsum', ['input', 'guide'], ['col_score'], equation='nchw,cab->nw'),
        helper.make_node('Einsum', ['input', 'guide'], ['paint'], equation='nchw,cab->cab'),
        helper.make_node('Cast', ['row_score'], ['row_hit_u'], to=2),
        helper.make_node('Cast', ['col_score'], ['col_hit_u'], to=2),
        helper.make_node('ArgMax', ['row_hit_u'], ['rmin'], axis=1, keepdims=0, select_last_index=0),
        helper.make_node('ArgMax', ['row_hit_u'], ['rmax'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('ArgMax', ['col_hit_u'], ['cmin'], axis=1, keepdims=0, select_last_index=0),
        helper.make_node('ArgMax', ['col_hit_u'], ['cmax'], axis=1, keepdims=0, select_last_index=1),
        helper.make_node('Cast', ['rmin'], ['rmin_i'], to=2),
        helper.make_node('Cast', ['rmax'], ['rmax_i'], to=2),
        helper.make_node('Cast', ['cmin'], ['cmin_i'], to=2),
        helper.make_node('Cast', ['cmax'], ['cmax_i'], to=2),
        helper.make_node('Sub', ['rmax_i', 'u2'], ['rmax_m2']),
        helper.make_node('Sub', ['cmax_i', 'u2'], ['cmax_m2']),
        helper.make_node('Sub', ['rmax_m2', 'rmin_i'], ['rspan']),
        helper.make_node('Sub', ['cmax_m2', 'cmin_i'], ['cspan']),
        helper.make_node('Sub', ['idx_r', 'rmin_i'], ['rdist']),
        helper.make_node('Sub', ['idx_c', 'cmin_i'], ['cdist']),
        helper.make_node('LessOrEqual', ['rdist', 'rspan'], ['rrange']),
        helper.make_node('LessOrEqual', ['cdist', 'cspan'], ['crange']),
        helper.make_node('Mod', ['rdist', 'rspan'], ['rmod'], fmod=0),
        helper.make_node('Mod', ['cdist', 'cspan'], ['cmod'], fmod=0),
        helper.make_node('Equal', ['rmod', 'u0'], ['hrow']),
        helper.make_node('Equal', ['cmod', 'u0'], ['vcol']),
        helper.make_node('Where', ['rrange', 'u1', 'u0'], ['row_base']),
        helper.make_node('Where', ['hrow', 'u2', 'row_base'], ['row_code']),
        helper.make_node('Where', ['crange', 'u1', 'u2'], ['col_base']),
        helper.make_node('Where', ['vcol', 'u0', 'col_base'], ['col_code']),
        helper.make_node('Pad', ['row_code', 'pad_span', 'u0', 'axis0'], ['row_code_p']),
        helper.make_node('Pad', ['col_code', 'pad_span', 'u2'], ['col_code_p']),
        helper.make_node('Greater', ['row_code_p', 'col_code_p'], ['border']),
        helper.make_node('Where', ['border', 'paint', 'input'], ['output']),
    ]
    value_infos = [
    ]
    return model('task224_live_exact', nodes, inits, output_dtype=1, opset=18, value_infos=value_infos)
