"""Task 030 — exact source reconstruction of current live graph.

Generated by reports/scripts/live_to_exact_source.py.
This owns the live ONNX graph in Python source; it is a control baseline,
not a semantic optimization.
"""
from onnx import TensorProto, helper
from ._exact import arr_b64, model, tensor


def build(task):
    inits = [
        tensor('sl_s', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==')),
        tensor('sl_e', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDQsKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAAAAAAAAAAIAAAAAAAAACgAAAAAAAAAKAAAAAAAAAA==')),
        tensor('sel1', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('sel2', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAgD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('sel4', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAAAAAAAAAAAAAAAAAACAPwAAAAAAAAAAAAAAAAAAAAAAAAAA')),
        tensor('cw', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDMwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAIA/CiuzPnDK+j22hS89ArB1PGDzqzsqsPA6pXMoOl3KazkkBqU4E/7mN32qITfISmI2VWCeNfmv3TRRJxs0Ji1ZMxX/lzLUwdQxTOcUMYdtUDCg35Evxy/MLrznDi4fCEgtT/+LLBz2wysIJgkrTfk/Kpdbhik=')),
        tensor('ar10', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAAAAAQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAA')),
        tensor('ten_i', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGk0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoKAAAA')),
        tensor('thr', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnPGY0JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKCksIH0gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoAAEhC')),
        tensor('mask5', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfHUxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoBAQEBAQAAAAAA')),
        tensor('W', arr_b64('k05VTVBZAQB2AHsnZGVzY3InOiAnfGkxJywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDEwLCA0LCAxLCAxKSwgfSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAoB////AAEAAAAAAQAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAA')),
    ]
    nodes = [
        helper.make_node('Slice', ['input', 'sl_s', 'sl_e'], ['m1f']),
        helper.make_node('Cast', ['m1f'], ['m1'], to=2),
        helper.make_node('Einsum', ['input', 'sel1', 'cw'], ['code1'], equation='nchw,c,w->'),
        helper.make_node('Einsum', ['input', 'sel2', 'cw'], ['code2'], equation='nchw,c,w->'),
        helper.make_node('Einsum', ['input', 'sel4', 'cw'], ['code4'], equation='nchw,c,w->'),
        helper.make_node('Div', ['code1', 'code2'], ['r2']),
        helper.make_node('Log', ['r2'], ['d2']),
        helper.make_node('Cast', ['d2'], ['di2'], to=6),
        helper.make_node('Mod', ['di2', 'ten_i'], ['adj2']),
        helper.make_node('Sub', ['ar10', 'adj2'], ['cols2']),
        helper.make_node('Gather', ['m1', 'cols2'], ['m2'], axis=3),
        helper.make_node('Div', ['code1', 'code4'], ['r4']),
        helper.make_node('Log', ['r4'], ['d4']),
        helper.make_node('Cast', ['d4'], ['di4'], to=6),
        helper.make_node('Mod', ['di4', 'ten_i'], ['adj4']),
        helper.make_node('Sub', ['ar10', 'adj4'], ['cols4']),
        helper.make_node('Gather', ['m1', 'cols4'], ['m4'], axis=3),
        helper.make_node('ReduceSum', ['input'], ['total'], keepdims=0),
        helper.make_node('Greater', ['total', 'thr'], ['is10b']),
        helper.make_node('Cast', ['is10b'], ['is10'], to=2),
        helper.make_node('Max', ['mask5', 'is10', 'm1'], ['valid']),
        helper.make_node('Concat', ['valid', 'm1', 'm2', 'm4'], ['A'], axis=1),
        helper.make_node('ConvInteger', ['A', 'W'], ['output'], pads=[0, 0, 20, 20]),
    ]
    value_infos = [
    ]
    return model('task030_live_exact', nodes, inits, output_dtype=6, opset=13, value_infos=value_infos)
